// Guards against i18n keys outliving the code that used them. The 16.08.2026 audit found 139 such
// keys in zh/en/de (~9% of the dictionary): whole blocks left behind by reworked scenes — `prep.*`
// and `progression.*` from the per-unit upgrade panel LevelPrepScene no longer draws, the per-scene
// `*.back` labels superseded by SceneHeader's shared `common.back`, ~28 `world.*` strings from the
// pre-rework world map. Nothing catches these: key parity across the three locales is
// compile-enforced (en.ts/de.ts are Record<TranslationKey, string>), and i18n-placeholder-parity
// pins the inside of the strings, but a key referenced by nobody type-checks and translates fine
// forever. Dead copy is not merely clutter — it is a trap for the next reader, who cannot tell
// "this screen shows this text" from "this screen used to".
//
// Rule: every key in zh.ts is either referenced by a literal in the source, or generated by one of
// the DYNAMIC_FAMILIES below.
//
// Why families with explicit domains, and not a list of allowed prefixes: a prefix allowlist is the
// thing that hid 14 of those 139 keys from the first pass of the audit. `t(`auction.${mat}`)` exists,
// so "allow auction.*" would have vouched for `auction.back`/`auction.seller`/`auction.tax` — none of
// which any material id can produce. A family names the *shape* and the *value domain*, so it covers
// exactly the keys the call site can actually build. Domains come from the real constant wherever one
// exists (CARD_DEFS, EQUIPMENT_DEFS, ACHIEVEMENTS, BUILDING_KEYS, AFFIX_FIELD_MAP, RANK_TIERS), so
// adding a card or a building needs no edit here; the short closed enums (slots, rarities, roles,
// tabs) are spelled out, and a new member failing this test is the intended outcome — it means a
// translation is missing.
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { zh } from '../src/i18n/locales/zh';
import { CARD_DEFS } from '../src/game/meta/cardDefs';
import { EQUIPMENT_DEFS } from '../src/game/meta/equipmentDefs';
// Direct relative imports rather than the `@nw/shared` alias (which points at the browser-safe SLG
// slice only) — same reasoning, and same precedent, as i18n.test.ts's equipment.ts import.
import { ACHIEVEMENTS } from '../../server/shared/src/achievements';
import { BUILDING_KEYS } from '../../server/shared/src/slg/city';
import { RANK_TIERS } from '../../server/shared/src/ladder';
import { AFFIX_FIELD_MAP } from '../../server/engine/src/balance/equipment';

const REPO = path.resolve(__dirname, '../..');
const LOCALE_DIR = path.resolve(__dirname, '../src/i18n/locales');

// server/ is scanned too: system mail arrives at the client as an i18n key chosen server-side
// (`subject: 'card.mail.rosterFull.subject'`), so those keys' only reference lives over there.
const SCAN_ROOTS = ['client/src', 'client/test', 'server'].map((p) => path.join(REPO, p));
const SKIP_DIR = /(^|[\\/])(node_modules|dist|coverage|\.git)([\\/]|$)/;
const SCANNED_EXT = /\.(ts|tsx|js|mjs|cjs|json)$/;

function sourceFiles(): string[] {
  const out: string[] = [];
  const walk = (p: string): void => {
    if (SKIP_DIR.test(p)) return;
    let st: fs.Stats;
    try { st = fs.statSync(p); } catch { return; }
    if (st.isDirectory()) { for (const e of fs.readdirSync(p)) walk(path.join(p, e)); return; }
    if (!SCANNED_EXT.test(p)) return;
    if (path.resolve(p).startsWith(LOCALE_DIR)) return; // the dictionaries are not references
    if (path.resolve(p) === __filename) return; // nor is this file's own allowlist
    out.push(p);
  };
  SCAN_ROOTS.forEach(walk);
  return out;
}

/**
 * Every quoted string in the source. Scanned over raw text rather than a parsed AST, which means
 * template-literal interiors are read too — `${t('roster.capacity')}` has to count as a reference —
 * and so are comments, which over-counts liveness. That bias is deliberate: a mention in a comment
 * keeping one key alive is a far cheaper failure than this test greenlighting a delete.
 */
function literalStrings(): Set<string> {
  const found = new Set<string>();
  const quoted = /'((?:[^'\\\n]|\\.)*)'|"((?:[^"\\\n]|\\.)*)"/g;
  const tick = /`([^`]*)`/g;
  for (const f of sourceFiles()) {
    const src = fs.readFileSync(f, 'utf8');
    for (const m of src.matchAll(quoted)) found.add(m[1] !== undefined ? m[1] : m[2]!);
    for (const m of src.matchAll(tick)) if (!m[1]!.includes('${')) found.add(m[1]!);
  }
  return found;
}

const cross = (...parts: ReadonlyArray<readonly string[]>): string[] =>
  parts.reduce<string[]>((acc, p) => acc.flatMap((a) => p.map((b) => a + b)), ['']);

const CARD_IDS = Object.keys(CARD_DEFS);
/** CardScene/detail.ts renders the skill line from `card.<id>.desc` only under this exact condition. */
const CARDS_WITH_SKILL = CARD_IDS.filter(
  (id) => CARD_DEFS[id]!.faction === 'anna' && CARD_DEFS[id]!.skillGrowth.some((v) => v > 0),
);

/**
 * Key shapes built at runtime, each paired with the exact value domain its call site can supply.
 *
 * `coverage` runs the table in the other direction as well:
 *  - 'complete' — every key the family can build must exist in the dictionary. This is the guard
 *    against the s_siege bug class (a domain grows, the translation does not, and the raw id goes
 *    on screen). Add an anna card or a building and this is what tells you a string is missing.
 *  - 'partial'  — the family deliberately outruns the dictionary; only liveness is checked. Both
 *    cases are justified inline, and 'partial' is not a place to park an unexplained hole.
 */
const DYNAMIC_FAMILIES: ReadonlyArray<{ why: string; keys: string[]; coverage: 'complete' | 'partial' }> = [
  // CardScene/detail.ts, list.ts, skins.ts, GachaScene, AuctionScene, DefenseEditorScene, mail.ts.
  // (Engine-roster cards — infantry/archer/… — are literal `nameKey:`/`descKey:` values in
  // engine/config.ts, so they need no family here; these are the meta character cards.)
  // .lore is required, not decorative: CardScene/detail.ts feeds it to the card's flip side with no
  // fallback, unlike CardCodexScene's storyText() which falls back to the blurb.
  { why: 't(`card.${defId}.{name,lore}`)', keys: cross(['card.'], CARD_IDS, ['.name', '.lore']), coverage: 'complete' },
  // Scoped to the cards that can actually reach the skill line — the tao roster is NO_SKILL, so it
  // renders roster.skillNone and a `card.<tao id>.desc` would be dead weight. Give a tao card a
  // skill growth curve and this family starts requiring its desc, which is the point.
  { why: 't(`card.${defId}.desc`) — skill line, anna faction with a nonzero skill curve', keys: cross(['card.'], CARDS_WITH_SKILL, ['.desc']), coverage: 'complete' },
  { why: 't(`equip.${defId}.name`)', keys: cross(['equip.'], Object.keys(EQUIPMENT_DEFS), ['.name']) , coverage: 'complete' },
  { why: 't(`equip.slot.${slot}`)', keys: cross(['equip.slot.'], ['weapon', 'armor', 'trinket']) , coverage: 'complete' },
  { why: 't(`equip.rarity.${rarity}`)', keys: cross(['equip.rarity.'], ['common', 'fine', 'rare', 'epic']) , coverage: 'complete' },
  // AFFIX_FIELD_MAP carries forward-compat ids (m_armor, s_lifesteal, s_regen,
  // s_matdrop, s_stamina, m_atkspd) that no roll table can currently produce, so they have no copy
  // yet. The rollable subset IS pinned complete — by i18n.test.ts, off MAIN_AFFIX_BY_SLOT +
  // SUB_AFFIX_POOL, which is the set that can actually reach a player's item.
  { why: 't(`affix.${id}`) — EquipmentScene/helpers.ts affixDesc', keys: cross(['affix.'], Object.keys(AFFIX_FIELD_MAP)) , coverage: 'partial' },
  { why: "t('material.' + kind)", keys: cross(['material.'], ['scrap', 'lead', 'binding']) , coverage: 'complete' },
  { why: "t('rarity.' + rarity) — GachaScene/page.ts", keys: cross(['rarity.'], ['common', 'rare', 'epic', 'legendary']) , coverage: 'complete' },
  // 'unranked' is the makeNewSave default (SaveData.ts / shared types.ts), not a RANK_TIERS entry.
  { why: "t('rank.' + rank)", keys: cross(['rank.'], ['unranked', ...RANK_TIERS.map((r) => r.id)]) , coverage: 'complete' },
  { why: "t('achievement.' + def.id + '.{name,desc}')", keys: cross(['achievement.'], ACHIEVEMENTS.map((a) => a.id), ['.name', '.desc']) , coverage: 'complete' },
  // CATEGORY_ORDER in AchievementScene.ts, filtered to categories present in the server's defs —
  // 'collection' has no achievements yet but the tab is wired and appears as soon as one lands.
  { why: "t('achievement.category.' + cat)", keys: cross(['achievement.category.'], ['pve', 'pvp', 'collection', 'progression']) , coverage: 'complete' },
  { why: 't(`city.bld.${key}`) — CityScene render/modals', keys: cross(['city.bld.'], BUILDING_KEYS) , coverage: 'complete' },
  { why: 't(`event.tasks.${task.kind}`)', keys: cross(['event.tasks.'], ['pve.clear', 'pvp.win', 'ad.watch']) , coverage: 'complete' },
  { why: 't(`friends.tab.${tab}`)', keys: cross(['friends.tab.'], ['friends', 'family', 'sect', 'world', 'mail']) , coverage: 'complete' },
  { why: 't(`world.season.${status}`)', keys: cross(['world.season.'], ['open', 'active', 'settling', 'closed']) , coverage: 'complete' },
  { why: 't(`family.${member.role}`) — FamilyScene/lists.ts', keys: cross(['family.'], ['leader', 'member', 'elder']) , coverage: 'complete' },
  // TutorialDirector walks objective/beat indices; the dictionary decides how far the walk goes.
  // TutorialDirector probes each variant and falls back when it echoes, so the
  // dictionary decides how far the walk goes: .done exists only for beats, .landscape only where a
  // wide-screen rewrite was actually needed. Requiring the full cross product would demand ~30
  // strings nobody wants written.
  { why: 't(`tutorial.o${n}.…`) / t(`tutorial.beat${i}.…`)', keys: cross(['tutorial.'], ['o1', 'o2', 'o3', 'o4', 'o5', 'o6', 'o7', 'beat1', 'beat2', 'beat3'], ['.title', '.body', '.done'], ['', '.landscape']) , coverage: 'partial' },
  { why: 'slgTitleKey() in shared/titles.ts → t(`title.slg.${id}.{full,short}`)', keys: cross(['title.slg.'], ['champion', 'top3'], ['.full', '.short']) , coverage: 'complete' },
  { why: 't(`auction.mail.${reason}.{subject,body}`) — FriendsScene/mail.ts', keys: cross(['auction.mail.'], ['sold', 'returned', 'proceeds', 'refund'], ['.subject', '.body']) , coverage: 'complete' },
  // Server mail whose body carries interpolation params is sent as `key|name=value|name2=value2`
  // (worldsvc season settlement, socialsvc join rejection); FriendsScene/mail.ts mailText() splits
  // the params off before t(), so these keys never appear as a bare literal on either side.
  { why: 'server mail sent in `key|param=value` form', keys: ['slg.settle.body', 'family.mail.rejected.body'] , coverage: 'complete' },
];

describe('i18n dictionary has no dead keys', () => {
  const files = sourceFiles();
  const referenced = literalStrings();
  const generated = new Set(DYNAMIC_FAMILIES.flatMap((f) => f.keys));

  // Canary (repo convention for source-scanning specs — a scan that silently matches nothing must
  // not be able to look like a pass). Here a broken scan would actually fail loudly rather than
  // vacuously, since an empty `referenced` marks every key dead; the canary is what says *why*.
  // The `common.back` probe is the sharper half: it is reached only through the exact shape this
  // scan exists to see — a bare `t('common.back')` inside a template literal in SceneHeader.ts.
  it('the source scan actually read the tree', () => {
    expect(files.length).toBeGreaterThan(1000);
    expect(referenced.size).toBeGreaterThan(10_000);
    expect(referenced.has('common.back')).toBe(true);
  });

  it('every zh.ts key is referenced by a literal or generated by a declared dynamic family', () => {
    const dead = Object.keys(zh).filter((k) => !referenced.has(k) && !generated.has(k));
    expect(dead).toEqual([]);
  });

  it('every key a `complete` family can build is actually translated', () => {
    // The other direction, and the one a player feels: a domain grows (new card, new building, new
    // achievement) but the copy does not, and t() renders the key itself on screen — the s_siege
    // bug in reverse. i18n.test.ts pins this for rollable affixes only; this extends it to every
    // family whose domain the dictionary is supposed to cover fully.
    const missing = DYNAMIC_FAMILIES
      .filter((f) => f.coverage === 'complete')
      .flatMap((f) => f.keys.filter((k) => !(k in zh)).map((k) => `${k}  (${f.why})`));
    expect(missing).toEqual([]);
  });

  it('every dynamic family still matches keys that exist (renamed prefixes stop vouching silently)', () => {
    // Staleness check on the table above. If a family's prefix is renamed (`equip.rarity.*` →
    // `equip.tier.*`) the old rule keeps happily vouching for nothing, and the day someone adds a
    // key under the stale prefix it is waved through. Requiring a family to still hit the
    // dictionary catches the rename at the rename, not months later.
    const orphaned = DYNAMIC_FAMILIES.filter((f) => !f.keys.some((k) => k in zh)).map((f) => f.why);
    expect(orphaned).toEqual([]);
  });
});
