// Regenerates `endStatsFixture.ts` — the end-of-match payload the layout sweep's `result` stop is
// handed — by PLAYING A REAL AI MATCH to its natural end and recording what the game actually
// produced.
//
// Skipped unless NW_CAPTURE=1, because it is not a test: it asserts nothing about layout, it takes
// as long as a match takes (minutes), and it would be pure cost on every sweep. It exists so the
// fixture has a provenance other than "someone typed plausible numbers".
//
// Why the sweep does not simply play the match itself: it would pay those minutes once per viewport,
// ten times over, to audit a screen whose content is fixed the instant the match ends. And why the
// fixture is not hand-written either — which is what it was until 2026-09-11: hand-written stats are
// a guess at the SHAPE as much as at the values. The first version left `killsByType`/`castsByType`
// empty objects, so the two widest rows on the screen — the per-unit-type breakdowns — rendered as
// nothing at all and the sweep audited a screen the player never sees.
//
//   Run: NW_CAPTURE=1 npx playwright test --config playwright.portrait.config.ts captureEndStats

import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { uid, registerAndEnterLobby, callCb, currentScreen } from './lib/nwE2E';

/** A match against the AI runs minutes, and the sweep's own per-test budget does not apply here. */
const MATCH_TIMEOUT_MS = 15 * 60_000;

test.describe('end-of-match stats fixture', () => {
  test('play one AI match and record its result payload', async ({ page }) => {
    test.skip(!process.env.NW_CAPTURE, 'set NW_CAPTURE=1 to regenerate test/browser/endStatsFixture.ts');
    test.setTimeout(MATCH_TIMEOUT_MS + 120_000);
    await registerAndEnterLobby(page, uid('capture'), 'CaptureStats');
    expect(await callCb(page, 'lobbyCb', 'onStartGame', ['AI'])).toBe(true);

    // Played out with no input at all: the AI wins, which is a real end state with real numbers on
    // both sides (the losing side's `damageTakenByBase` is the widest number on the screen). Waiting
    // on the SCREEN rather than on a clock — a match has no fixed length.
    await page.waitForFunction(
      () => window.__nwE2E?.state?.screen === 'result',
      null,
      { timeout: MATCH_TIMEOUT_MS, polling: 1_000 },
    );
    expect(await currentScreen(page)).toBe('result');

    // `showResult` is handed one `ResultViewProps`; only its data half is a fixture — `cb` is the
    // live scene callbacks bag and `localOwner` is whichever side this capture happened to play.
    const captured = await page.evaluate(() => {
      const props = window.__nwE2E?.state?.resultArgs?.[0] as
        { winner?: number | null; stats?: unknown[] } | undefined;
      if (!props || !Array.isArray(props.stats)) return null;
      return JSON.parse(JSON.stringify({ winner: props.winner ?? null, stats: props.stats })) as
        { winner: number | null; stats: unknown[] };
    });
    expect(captured, 'ResultScene was shown without winner/stats').not.toBeNull();
    expect(captured!.stats.length, 'expected one PlayerStats per side').toBe(2);

    const file = path.join('test', 'browser', 'endStatsFixture.ts');
    fs.writeFileSync(file, `${HEADER}
/** The winner as onGameEnd takes it: the owning side's id, or null for a draw. */
export const REAL_END_WINNER: number | null = ${JSON.stringify(captured!.winner)};

/** Both sides' PlayerStats, exactly as the engine produced them. */
export const REAL_END_STATS: Record<string, unknown>[] = ${JSON.stringify(captured!.stats, null, 2)};
`);
    // eslint-disable-next-line no-console
    console.log(`wrote ${file}`);
  });
});

const HEADER = `// GENERATED by captureEndStats.spec.ts (NW_CAPTURE=1) — do not hand-edit.
//
// The arguments a real, played-out AI match handed ResultScene, captured on ${new Date().toISOString().slice(0, 10)}.
// The layout sweep replays them into the \`result\` stop instead of playing the match again on every
// viewport; see captureEndStats.spec.ts for why this is a recording rather than a fixture.
`;
