// ⚠️ PROVISIONAL — hand-written, NOT yet recorded from a real match.
//
// This file is normally GENERATED by captureEndStats.spec.ts (`NW_CAPTURE=1`), which plays one AI
// match to its natural end and writes down what the engine handed ResultScene. That run has not
// succeeded yet, and the reason is worth keeping: **a match in which the player does nothing does
// not end.** Started 2026-09-11 14:23 and abandoned at the spec's 15-minute ceiling, still in
// `screen: 'game'` — the AI alone never took the player's base down. So the recorder needs the
// harness to actually play (or to exit through the surrender path, which ends a real match with
// real, if small, numbers). Until then these values are a stand-in and should not be cited as
// evidence of anything about a real match.
//
// What is NOT provisional is the shape. The version this replaces left `killsByType` and
// `castsByType` as empty objects, which meant the sweep's `result` stop audited a screen with its
// two widest blocks missing — the per-unit-type breakdowns simply did not render. Those are
// populated here, which is most of what this stop is for.
//
// The extreme end of the range is a separate stop (`result+extreme`, portraitLayout.spec.ts): a
// recorded match is realistic, and realistic is the one thing it cannot be while also being
// extreme.

/** The winner as onGameEnd takes it: the owning side's id, or null for a draw. */
export const REAL_END_WINNER: number | null = 0;

/** Both sides' PlayerStats (server/engine/src/types/runtime.ts). */
export const REAL_END_STATS: Record<string, unknown>[] = [
  {
    owner: 0,
    damageDealtToBase: 5240,
    damageTakenByBase: 1470,
    unitsSent: 62,
    unitsKilled: 48,
    spellHits: 17,
    killsByType: { infantry: 21, archer: 14, cavalry: 9, medic: 4 },
    castsByType: { fireball: 11, heal: 6 },
    buildingSurvivalTicks: 9840,
    goldSpent: 1310,
  },
  {
    owner: 1,
    damageDealtToBase: 1470,
    damageTakenByBase: 5240,
    unitsSent: 58,
    unitsKilled: 39,
    spellHits: 12,
    killsByType: { infantry: 18, archer: 11, cavalry: 7, siege: 3 },
    castsByType: { fireball: 8, rally: 4 },
    buildingSurvivalTicks: 9840,
    goldSpent: 1180,
  },
];
