// Equipment system (E2 craft / E3 enhance·salvage / E4 equip / E6 reforge) + card feed/lock (CC-1).
import type { SaveData, EquipmentInstance, EquipSlot } from '../../game/meta/SaveData';
import { type Constructor, type ApiClientBaseCtor } from './base';

export interface EquipmentApi {
  craftEquipment(defId: string, idempotencyKey: string): Promise<{ save: SaveData; instance: EquipmentInstance }>;
  enhanceEquipment(
    instanceId: string,
    idempotencyKey: string,
    useProtect?: boolean,
  ): Promise<{ success: boolean; instance: EquipmentInstance; save: SaveData }>;
  salvageEquipment(
    instanceIds: string[],
    idempotencyKey: string,
  ): Promise<{ refunded: Record<string, number>; save: SaveData }>;
  equipEquipment(slot: EquipSlot, instanceId: string | null, cardInstanceId: string): Promise<{ save: SaveData }>;
  feedCards(
    targetCardId: string,
    materialCardIds: string[],
    idempotencyKey: string,
  ): Promise<{ save: SaveData; levelsGained: number }>;
  setCardLock(cardInstanceId: string, locked: boolean): Promise<{ save: SaveData }>;
  reforgeEquipment(
    targetId: string,
    materialId: string,
    idempotencyKey: string,
  ): Promise<{ instance: EquipmentInstance; save: SaveData }>;
}

export function EquipmentMixin<TBase extends ApiClientBaseCtor>(Base: TBase): TBase & Constructor<EquipmentApi> {
  return class extends Base {
    // ── Equipment system (E2 craft / E3 enhance·salvage / E4 equip, server-authoritative, requires login token) ────
    // All equipment actions return the server-authoritative SaveData (equipmentInv/gear/materials/wallet as per server).
    // idempotencyKey is generated by the caller (enhance binds to the dice roll result, so replays don't change the outcome).

    /** Craft one +0 base equipment piece (E2): deducts stationery materials → adds to inventory. Insufficient materials → 402; inventory full → 409 INVENTORY_FULL. */
    async craftEquipment(
      defId: string,
      idempotencyKey: string,
    ): Promise<{ save: SaveData; instance: EquipmentInstance }> {
      return this.post<{ save: SaveData; instance: EquipmentInstance }>('/equipment/craft', {
        defId,
        idempotencyKey,
      });
    }

    /**
     * Enhance one equipment piece (E3): server rolls the dice; on success level+1, on failure no level drop (success=false); materials+coins are deducted in both cases.
     * Already max level → 409 ENHANCE_MAX_LEVEL; insufficient materials → 402 INSUFFICIENT_MATERIALS; insufficient coins → 402 INSUFFICIENT_FUNDS.
     */
    async enhanceEquipment(
      instanceId: string,
      idempotencyKey: string,
      useProtect?: boolean,
    ): Promise<{ success: boolean; instance: EquipmentInstance; save: SaveData }> {
      return this.post<{ success: boolean; instance: EquipmentInstance; save: SaveData }>(
        '/equipment/enhance',
        { instanceId, idempotencyKey, ...(useProtect ? { useProtect: true } : {}) },
      );
    }

    /** Salvage a batch of equipment (E3): +0~4 pieces refund 70% of crafting materials and are removed from inventory. +5 / equipped / locked → 409. Returns the total refunded materials. */
    async salvageEquipment(
      instanceIds: string[],
      idempotencyKey: string,
    ): Promise<{ refunded: Record<string, number>; save: SaveData }> {
      return this.post<{ refunded: Record<string, number>; save: SaveData }>('/equipment/salvage', {
        instanceIds,
        idempotencyKey,
      });
    }

    /**
     * Equip / unequip one equipment piece (E4, CC-1): instanceId=null unequips the slot.
     * cardInstanceId required (CC-1 — equipment now lives on the card, not on a global loadout).
     * Slot incompatible with equipment definition → 400 INVALID_SLOT; instance not found → 404.
     */
    async equipEquipment(
      slot: EquipSlot,
      instanceId: string | null,
      cardInstanceId: string,
    ): Promise<{ save: SaveData }> {
      return this.post<{ save: SaveData }>('/equipment/equip', {
        slot,
        instanceId,
        cardInstanceId,
      });
    }

    /**
     * Feed cards (CC-1): consumes materialCardIds (same-faction), adds XP to targetCardId.
     * Returns the updated SaveData; feed target must not be locked.
     * Material cards that are locked or deployed → 409 CARD_LOCKED.
     */
    async feedCards(
      targetCardId: string,
      materialCardIds: string[],
      idempotencyKey: string,
    ): Promise<{ save: SaveData; levelsGained: number }> {
      return this.post<{ save: SaveData; levelsGained: number }>('/cards/feed', {
        targetId: targetCardId,
        materialIds: materialCardIds,
        idempotencyKey,
      });
    }

    /**
     * Toggle card lock (CC-4 client helper): calls POST /cards/lock or /cards/unlock.
     * Locked cards cannot be used as feed material (CC4).
     */
    async setCardLock(cardInstanceId: string, locked: boolean): Promise<{ save: SaveData }> {
      return this.post<{ save: SaveData }>(locked ? '/cards/lock' : '/cards/unlock', { cardInstanceId });
    }

    /** Reforge one equipment piece (E6): consumes materialId, re-rolls targetId's secondary affixes; primary affix unchanged. */
    async reforgeEquipment(
      targetId: string,
      materialId: string,
      idempotencyKey: string,
    ): Promise<{ instance: EquipmentInstance; save: SaveData }> {
      return this.post<{ instance: EquipmentInstance; save: SaveData }>('/equipment/reforge', {
        targetId,
        materialId,
        idempotencyKey,
      });
    }
  };
}
