// Equipment system (E2 craft / E3 enhance·salvage / E4 equip / E6 reforge) + card feed/lock (CC-1).
import type {
  SaveData,
  LeanSaveResponse,
  EquipmentInstance,
  EquipSlot,
  CardInstance,
} from '../../game/meta/SaveData';
import type { ApiClientCore } from './core';

export interface EquipmentApi {
  craftEquipment(
    defId: string,
    idempotencyKey: string
  ): Promise<{ save: LeanSaveResponse; instance: EquipmentInstance }>;
  enhanceEquipment(
    instanceId: string,
    idempotencyKey: string,
    useProtect?: boolean
  ): Promise<{ success: boolean; instance: EquipmentInstance; save: LeanSaveResponse }>;
  salvageEquipment(
    instanceIds: string[],
    idempotencyKey: string
  ): Promise<{ refunded: Record<string, number>; save: LeanSaveResponse }>;
  equipEquipment(
    slot: EquipSlot,
    instanceId: string | null,
    cardInstanceId: string
  ): Promise<{ save: LeanSaveResponse }>;
  fuseCards(
    targetCardId: string,
    materialCardIds: string[],
    idempotencyKey: string
  ): Promise<{ save: SaveData; card: CardInstance }>;
  setCardLock(cardInstanceId: string, locked: boolean): Promise<{ save: SaveData }>;
  reforgeEquipment(
    targetId: string,
    materialId: string,
    idempotencyKey: string
  ): Promise<{ instance: EquipmentInstance; save: LeanSaveResponse }>;
  sellSkin(
    skinId: string,
    idempotencyKey: string
  ): Promise<{ credited: number; coinsAfter: number; save: SaveData }>;
}

/** Equipment/card-fuse/card-lock domain (see ../ApiClient.ts assembly + ./core.ts for the shared transport). */
export class EquipmentService implements EquipmentApi {
  constructor(private readonly core: ApiClientCore) {}

  // ── Equipment system (E2 craft / E3 enhance·salvage / E4 equip, server-authoritative, requires login token) ────
  // craft/enhance/salvage/equip/reforge return a lean `save` (equipmentInv: null, EQUIPMENT_DESIGN §3.3 phase 2) —
  // the caller already has what changed via `instance` / the instanceIds/materialId it just sent, so these must be
  // adopted via SaveManager.adoptServerPartial, never the plain adoptServer (see LeanSaveResponse doc comment).
  // idempotencyKey is generated by the caller (enhance binds to the dice roll result, so replays don't change the outcome).

  /** Craft one +0 base equipment piece (E2): deducts stationery materials → adds to inventory. Insufficient materials → 402; inventory full → 409 INVENTORY_FULL. */
  async craftEquipment(
    defId: string,
    idempotencyKey: string
  ): Promise<{ save: LeanSaveResponse; instance: EquipmentInstance }> {
    return this.core.post<{ save: LeanSaveResponse; instance: EquipmentInstance }>(
      '/equipment/craft',
      {
        defId,
        idempotencyKey,
      }
    );
  }

  /**
   * Enhance one equipment piece (E3): server rolls the dice; on success level+1, on failure no level drop (success=false); materials+coins are deducted in both cases.
   * Already max level → 409 ENHANCE_MAX_LEVEL; insufficient materials → 402 INSUFFICIENT_MATERIALS; insufficient coins → 402 INSUFFICIENT_FUNDS.
   */
  async enhanceEquipment(
    instanceId: string,
    idempotencyKey: string,
    useProtect?: boolean
  ): Promise<{ success: boolean; instance: EquipmentInstance; save: LeanSaveResponse }> {
    return this.core.post<{
      success: boolean;
      instance: EquipmentInstance;
      save: LeanSaveResponse;
    }>('/equipment/enhance', {
      instanceId,
      idempotencyKey,
      ...(useProtect ? { useProtect: true } : {}),
    });
  }

  /** Salvage a batch of equipment (E3): +0~4 pieces refund 70% of crafting materials and are removed from inventory. +5 / equipped / locked → 409. Returns the total refunded materials. */
  async salvageEquipment(
    instanceIds: string[],
    idempotencyKey: string
  ): Promise<{ refunded: Record<string, number>; save: LeanSaveResponse }> {
    return this.core.post<{ refunded: Record<string, number>; save: LeanSaveResponse }>(
      '/equipment/salvage',
      {
        instanceIds,
        idempotencyKey,
      }
    );
  }

  /**
   * Equip / unequip one equipment piece (E4, CC-1): instanceId=null unequips the slot.
   * cardInstanceId required (CC-1 — equipment now lives on the card, not on a global loadout).
   * Slot incompatible with equipment definition → 400 INVALID_SLOT; instance not found → 404.
   */
  async equipEquipment(
    slot: EquipSlot,
    instanceId: string | null,
    cardInstanceId: string
  ): Promise<{ save: LeanSaveResponse }> {
    return this.core.post<{ save: LeanSaveResponse }>('/equipment/equip', {
      slot,
      instanceId,
      cardInstanceId,
    });
  }

  /**
   * Fuse cards (CC-1, fusion redesign): consumes exactly 5 materialCardIds (same faction, same
   * level as target), raises targetCardId one level. Returns the updated SaveData + target card.
   * Target must not be locked; material cards that are locked or deployed → 409 CARD_LOCKED.
   */
  async fuseCards(
    targetCardId: string,
    materialCardIds: string[],
    idempotencyKey: string
  ): Promise<{ save: SaveData; card: CardInstance }> {
    return this.core.post<{ save: SaveData; card: CardInstance }>('/cards/fuse', {
      targetId: targetCardId,
      materialIds: materialCardIds,
      idempotencyKey,
    });
  }

  /**
   * Toggle card lock (CC-4 client helper): calls POST /cards/lock or /cards/unlock.
   * Locked cards cannot be used as fusion material (CC4).
   */
  async setCardLock(cardInstanceId: string, locked: boolean): Promise<{ save: SaveData }> {
    return this.core.post<{ save: SaveData }>(locked ? '/cards/lock' : '/cards/unlock', {
      cardInstanceId,
    });
  }

  /** Reforge one equipment piece (E6): consumes materialId, re-rolls targetId's secondary affixes; primary affix unchanged. */
  async reforgeEquipment(
    targetId: string,
    materialId: string,
    idempotencyKey: string
  ): Promise<{ instance: EquipmentInstance; save: LeanSaveResponse }> {
    return this.core.post<{ instance: EquipmentInstance; save: LeanSaveResponse }>(
      '/equipment/reforge',
      {
        targetId,
        materialId,
        idempotencyKey,
      }
    );
  }

  /**
   * Sell one surplus skin instance to the system for coins (ITEM_IDENTITY_DESIGN.md task1,
   * 2026-08-08) — player-initiated only, never automatic on a gacha duplicate. Refuses to sell the
   * last remaining instance of a currently-equipped skin → 409 SKIN_IN_USE; not owned → 404 SKIN_NOT_FOUND.
   */
  async sellSkin(
    skinId: string,
    idempotencyKey: string
  ): Promise<{ credited: number; coinsAfter: number; save: SaveData }> {
    return this.core.post<{ credited: number; coinsAfter: number; save: SaveData }>('/skins/sell', {
      skinId,
      idempotencyKey,
    });
  }
}
