// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: transport.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "nw.transport";

/** ── 房间 ────────────────────────────────────────────── */
export enum RoomPhase {
  WAITING = 0,
  READY = 1,
  COUNTDOWN = 2,
  IN_MATCH = 3,
  OVER = 4,
  UNRECOGNIZED = -1,
}

export enum MatchMode {
  FRIENDLY = 0,
  RANKED = 1,
  UNRECOGNIZED = -1,
}

export interface PlayerSlot {
  side: number;
  /** 展示昵称（displayName），非 accountId */
  name: string;
  ready: boolean;
  connected: boolean;
  /** 9 位数字公开 id（玩家交流 / 投诉用；accountId 仅服务器内部） */
  publicId: string;
}

/** ── 锁步帧（M14：模拟 30Hz，网络 10Hz 批次 = 3 帧）────── */
export interface SideCmd {
  side: number;
  /** game.proto PlayerCommand[]，对服务器 opaque */
  commands: Uint8Array;
}

export interface FrameCmds {
  frame: number;
  /** 单个 sim 帧的指令 */
  cmds: SideCmd[];
}

export interface FrameBatch {
  /** 水位：客户端可推进到的帧 */
  toFrame: number;
  /** 仅列非空帧；空窗只有 to_frame */
  frames: FrameCmds[];
}

/** ── 客户端 → 服务器 ────────────────────────────────── */
export interface RoomCreate {
  mode: MatchMode;
}

export interface RoomJoin {
  code: string;
}

export interface RoomReady {
  ready: boolean;
}

export interface RoomLeave {
}

export interface RoomStart {
}

export interface CmdSubmit {
  commands: Uint8Array;
}

export interface MatchResult {
  stateHash: string;
  winnerSide: number;
}

export interface ConnResume {
  roomId: string;
  lastFrame: number;
}

export interface Ping {
}

/**
 * ── 对等裁判反作弊（Phase C，单裁判）─────────────────────
 * hash 不一致的 ranked 局，meta 挑一名高配空闲在线玩家做无头复算裁决。
 * client_caps：玩家连上 gateway 后上报本机能否承担复算（控制面）。
 */
export interface ClientCaps {
  canJudge: boolean;
}

/** judge_verdict：裁判客户端复算完终局后回报（控制面）。 */
export interface JudgeVerdict {
  requestId: string;
  /** 复算得到的终局 hash（与 match_result.state_hash 同构） */
  stateHash: string;
  winnerSide: number;
  /** 复算成功（版本匹配 + 跑到终局） */
  ok: boolean;
}

export interface ClientMsg {
  roomCreate?: RoomCreate | undefined;
  roomJoin?: RoomJoin | undefined;
  roomReady?: RoomReady | undefined;
  roomLeave?: RoomLeave | undefined;
  roomStart?: RoomStart | undefined;
  cmdSubmit?: CmdSubmit | undefined;
  matchResult?: MatchResult | undefined;
  connResume?: ConnResume | undefined;
  ping?: Ping | undefined;
  clientCaps?: ClientCaps | undefined;
  judgeVerdict?: JudgeVerdict | undefined;
}

/** ── 服务器 → 客户端 ────────────────────────────────── */
export interface RoomState {
  code: string;
  players: PlayerSlot[];
  phase: RoomPhase;
}

export interface MatchStart {
  roomId: string;
  mode: MatchMode;
  seed: number;
  startFrame: number;
  localSide: number;
}

export interface ConnResync {
  seed: number;
  startFrame: number;
  /** 非空帧日志 */
  log: FrameCmds[];
  curFrame: number;
}

/**
 * 配对 / 房主开局成功（gateway 控制面推，M18/M20）。客户端据此连 game 数据面 WS：
 * wss://<game_url>?ticket=<ticket>。ticket 对客户端 opaque（HMAC-JWT，仅 game 验签）。
 */
export interface MatchFound {
  /** 分配到的 gameserver 公开 WS 地址 */
  gameUrl: string;
  /** matchsvc 签名票据（含 room_id/seed/side/mode/opponent） */
  ticket: string;
}

export interface PeerDc {
  side: number;
  graceMs: number;
}

export interface EloDelta {
  delta: number;
  after: number;
  rankAfter: string;
}

export interface MatchOver {
  winnerSide: number;
  /** base | disconnect | mismatch */
  reason: string;
  mismatch: boolean;
  /** 仅 ranked */
  elo?: EloDelta | undefined;
}

export interface RoomError {
  code: string;
  message: string;
}

export interface Pong {
}

/**
 * 裁判请求（gateway 控制面推给被选中的裁判客户端，Phase C）。客户端用 frames + seed
 * 无头复算整局，得到终局 hash + winner_side，经 judge_verdict 回报。frames 与
 * conn_resync.log 同构（仅非空帧；command bytes 仍 game.proto opaque）。
 */
export interface JudgeRequest {
  requestId: string;
  seed: number;
  mode: MatchMode;
  endFrame: number;
  frames: FrameCmds[];
}

export interface ServerMsg {
  roomState?: RoomState | undefined;
  matchStart?: MatchStart | undefined;
  frameBatch?: FrameBatch | undefined;
  connResync?: ConnResync | undefined;
  peerDc?: PeerDc | undefined;
  matchOver?: MatchOver | undefined;
  roomError?: RoomError | undefined;
  pong?: Pong | undefined;
  matchFound?: MatchFound | undefined;
  judgeRequest?: JudgeRequest | undefined;
}

/** 线上每帧一个 Envelope */
export interface Envelope {
  client?: ClientMsg | undefined;
  server?: ServerMsg | undefined;
}

function createBasePlayerSlot(): PlayerSlot {
  return { side: 0, name: "", ready: false, connected: false, publicId: "" };
}

export const PlayerSlot: MessageFns<PlayerSlot> = {
  encode(message: PlayerSlot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.side !== 0) {
      writer.uint32(8).uint32(message.side);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.ready !== false) {
      writer.uint32(24).bool(message.ready);
    }
    if (message.connected !== false) {
      writer.uint32(32).bool(message.connected);
    }
    if (message.publicId !== "") {
      writer.uint32(42).string(message.publicId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerSlot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerSlot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.side = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.ready = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.connected = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.publicId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PlayerSlot>, I>>(base?: I): PlayerSlot {
    return PlayerSlot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerSlot>, I>>(object: I): PlayerSlot {
    const message = createBasePlayerSlot();
    message.side = object.side ?? 0;
    message.name = object.name ?? "";
    message.ready = object.ready ?? false;
    message.connected = object.connected ?? false;
    message.publicId = object.publicId ?? "";
    return message;
  },
};

function createBaseSideCmd(): SideCmd {
  return { side: 0, commands: new Uint8Array(0) };
}

export const SideCmd: MessageFns<SideCmd> = {
  encode(message: SideCmd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.side !== 0) {
      writer.uint32(8).uint32(message.side);
    }
    if (message.commands.length !== 0) {
      writer.uint32(18).bytes(message.commands);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SideCmd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSideCmd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.side = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.commands = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SideCmd>, I>>(base?: I): SideCmd {
    return SideCmd.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SideCmd>, I>>(object: I): SideCmd {
    const message = createBaseSideCmd();
    message.side = object.side ?? 0;
    message.commands = object.commands ?? new Uint8Array(0);
    return message;
  },
};

function createBaseFrameCmds(): FrameCmds {
  return { frame: 0, cmds: [] };
}

export const FrameCmds: MessageFns<FrameCmds> = {
  encode(message: FrameCmds, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frame !== 0) {
      writer.uint32(8).uint32(message.frame);
    }
    for (const v of message.cmds) {
      SideCmd.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameCmds {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameCmds();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frame = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cmds.push(SideCmd.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FrameCmds>, I>>(base?: I): FrameCmds {
    return FrameCmds.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FrameCmds>, I>>(object: I): FrameCmds {
    const message = createBaseFrameCmds();
    message.frame = object.frame ?? 0;
    message.cmds = object.cmds?.map((e) => SideCmd.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFrameBatch(): FrameBatch {
  return { toFrame: 0, frames: [] };
}

export const FrameBatch: MessageFns<FrameBatch> = {
  encode(message: FrameBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.toFrame !== 0) {
      writer.uint32(8).uint32(message.toFrame);
    }
    for (const v of message.frames) {
      FrameCmds.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameBatch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.toFrame = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.frames.push(FrameCmds.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FrameBatch>, I>>(base?: I): FrameBatch {
    return FrameBatch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FrameBatch>, I>>(object: I): FrameBatch {
    const message = createBaseFrameBatch();
    message.toFrame = object.toFrame ?? 0;
    message.frames = object.frames?.map((e) => FrameCmds.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRoomCreate(): RoomCreate {
  return { mode: 0 };
}

export const RoomCreate: MessageFns<RoomCreate> = {
  encode(message: RoomCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mode !== 0) {
      writer.uint32(8).int32(message.mode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RoomCreate>, I>>(base?: I): RoomCreate {
    return RoomCreate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomCreate>, I>>(object: I): RoomCreate {
    const message = createBaseRoomCreate();
    message.mode = object.mode ?? 0;
    return message;
  },
};

function createBaseRoomJoin(): RoomJoin {
  return { code: "" };
}

export const RoomJoin: MessageFns<RoomJoin> = {
  encode(message: RoomJoin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomJoin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomJoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RoomJoin>, I>>(base?: I): RoomJoin {
    return RoomJoin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomJoin>, I>>(object: I): RoomJoin {
    const message = createBaseRoomJoin();
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseRoomReady(): RoomReady {
  return { ready: false };
}

export const RoomReady: MessageFns<RoomReady> = {
  encode(message: RoomReady, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ready !== false) {
      writer.uint32(8).bool(message.ready);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomReady {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomReady();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ready = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RoomReady>, I>>(base?: I): RoomReady {
    return RoomReady.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomReady>, I>>(object: I): RoomReady {
    const message = createBaseRoomReady();
    message.ready = object.ready ?? false;
    return message;
  },
};

function createBaseRoomLeave(): RoomLeave {
  return {};
}

export const RoomLeave: MessageFns<RoomLeave> = {
  encode(_: RoomLeave, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomLeave {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomLeave();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RoomLeave>, I>>(base?: I): RoomLeave {
    return RoomLeave.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomLeave>, I>>(_: I): RoomLeave {
    const message = createBaseRoomLeave();
    return message;
  },
};

function createBaseRoomStart(): RoomStart {
  return {};
}

export const RoomStart: MessageFns<RoomStart> = {
  encode(_: RoomStart, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomStart {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomStart();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RoomStart>, I>>(base?: I): RoomStart {
    return RoomStart.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomStart>, I>>(_: I): RoomStart {
    const message = createBaseRoomStart();
    return message;
  },
};

function createBaseCmdSubmit(): CmdSubmit {
  return { commands: new Uint8Array(0) };
}

export const CmdSubmit: MessageFns<CmdSubmit> = {
  encode(message: CmdSubmit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.commands.length !== 0) {
      writer.uint32(10).bytes(message.commands);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CmdSubmit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCmdSubmit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.commands = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CmdSubmit>, I>>(base?: I): CmdSubmit {
    return CmdSubmit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CmdSubmit>, I>>(object: I): CmdSubmit {
    const message = createBaseCmdSubmit();
    message.commands = object.commands ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMatchResult(): MatchResult {
  return { stateHash: "", winnerSide: 0 };
}

export const MatchResult: MessageFns<MatchResult> = {
  encode(message: MatchResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stateHash !== "") {
      writer.uint32(10).string(message.stateHash);
    }
    if (message.winnerSide !== 0) {
      writer.uint32(16).uint32(message.winnerSide);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stateHash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.winnerSide = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MatchResult>, I>>(base?: I): MatchResult {
    return MatchResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchResult>, I>>(object: I): MatchResult {
    const message = createBaseMatchResult();
    message.stateHash = object.stateHash ?? "";
    message.winnerSide = object.winnerSide ?? 0;
    return message;
  },
};

function createBaseConnResume(): ConnResume {
  return { roomId: "", lastFrame: 0 };
}

export const ConnResume: MessageFns<ConnResume> = {
  encode(message: ConnResume, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    if (message.lastFrame !== 0) {
      writer.uint32(16).uint32(message.lastFrame);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnResume {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnResume();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lastFrame = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ConnResume>, I>>(base?: I): ConnResume {
    return ConnResume.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnResume>, I>>(object: I): ConnResume {
    const message = createBaseConnResume();
    message.roomId = object.roomId ?? "";
    message.lastFrame = object.lastFrame ?? 0;
    return message;
  },
};

function createBasePing(): Ping {
  return {};
}

export const Ping: MessageFns<Ping> = {
  encode(_: Ping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePing();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Ping>, I>>(base?: I): Ping {
    return Ping.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ping>, I>>(_: I): Ping {
    const message = createBasePing();
    return message;
  },
};

function createBaseClientCaps(): ClientCaps {
  return { canJudge: false };
}

export const ClientCaps: MessageFns<ClientCaps> = {
  encode(message: ClientCaps, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.canJudge !== false) {
      writer.uint32(8).bool(message.canJudge);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientCaps {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientCaps();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.canJudge = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ClientCaps>, I>>(base?: I): ClientCaps {
    return ClientCaps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientCaps>, I>>(object: I): ClientCaps {
    const message = createBaseClientCaps();
    message.canJudge = object.canJudge ?? false;
    return message;
  },
};

function createBaseJudgeVerdict(): JudgeVerdict {
  return { requestId: "", stateHash: "", winnerSide: 0, ok: false };
}

export const JudgeVerdict: MessageFns<JudgeVerdict> = {
  encode(message: JudgeVerdict, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.stateHash !== "") {
      writer.uint32(18).string(message.stateHash);
    }
    if (message.winnerSide !== 0) {
      writer.uint32(24).uint32(message.winnerSide);
    }
    if (message.ok !== false) {
      writer.uint32(32).bool(message.ok);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JudgeVerdict {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJudgeVerdict();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stateHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.winnerSide = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JudgeVerdict>, I>>(base?: I): JudgeVerdict {
    return JudgeVerdict.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JudgeVerdict>, I>>(object: I): JudgeVerdict {
    const message = createBaseJudgeVerdict();
    message.requestId = object.requestId ?? "";
    message.stateHash = object.stateHash ?? "";
    message.winnerSide = object.winnerSide ?? 0;
    message.ok = object.ok ?? false;
    return message;
  },
};

function createBaseClientMsg(): ClientMsg {
  return {
    roomCreate: undefined,
    roomJoin: undefined,
    roomReady: undefined,
    roomLeave: undefined,
    roomStart: undefined,
    cmdSubmit: undefined,
    matchResult: undefined,
    connResume: undefined,
    ping: undefined,
    clientCaps: undefined,
    judgeVerdict: undefined,
  };
}

export const ClientMsg: MessageFns<ClientMsg> = {
  encode(message: ClientMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomCreate !== undefined) {
      RoomCreate.encode(message.roomCreate, writer.uint32(10).fork()).join();
    }
    if (message.roomJoin !== undefined) {
      RoomJoin.encode(message.roomJoin, writer.uint32(18).fork()).join();
    }
    if (message.roomReady !== undefined) {
      RoomReady.encode(message.roomReady, writer.uint32(26).fork()).join();
    }
    if (message.roomLeave !== undefined) {
      RoomLeave.encode(message.roomLeave, writer.uint32(34).fork()).join();
    }
    if (message.roomStart !== undefined) {
      RoomStart.encode(message.roomStart, writer.uint32(42).fork()).join();
    }
    if (message.cmdSubmit !== undefined) {
      CmdSubmit.encode(message.cmdSubmit, writer.uint32(50).fork()).join();
    }
    if (message.matchResult !== undefined) {
      MatchResult.encode(message.matchResult, writer.uint32(58).fork()).join();
    }
    if (message.connResume !== undefined) {
      ConnResume.encode(message.connResume, writer.uint32(66).fork()).join();
    }
    if (message.ping !== undefined) {
      Ping.encode(message.ping, writer.uint32(74).fork()).join();
    }
    if (message.clientCaps !== undefined) {
      ClientCaps.encode(message.clientCaps, writer.uint32(82).fork()).join();
    }
    if (message.judgeVerdict !== undefined) {
      JudgeVerdict.encode(message.judgeVerdict, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomCreate = RoomCreate.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.roomJoin = RoomJoin.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.roomReady = RoomReady.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.roomLeave = RoomLeave.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.roomStart = RoomStart.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cmdSubmit = CmdSubmit.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.matchResult = MatchResult.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.connResume = ConnResume.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.ping = Ping.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.clientCaps = ClientCaps.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.judgeVerdict = JudgeVerdict.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ClientMsg>, I>>(base?: I): ClientMsg {
    return ClientMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientMsg>, I>>(object: I): ClientMsg {
    const message = createBaseClientMsg();
    message.roomCreate = (object.roomCreate !== undefined && object.roomCreate !== null)
      ? RoomCreate.fromPartial(object.roomCreate)
      : undefined;
    message.roomJoin = (object.roomJoin !== undefined && object.roomJoin !== null)
      ? RoomJoin.fromPartial(object.roomJoin)
      : undefined;
    message.roomReady = (object.roomReady !== undefined && object.roomReady !== null)
      ? RoomReady.fromPartial(object.roomReady)
      : undefined;
    message.roomLeave = (object.roomLeave !== undefined && object.roomLeave !== null)
      ? RoomLeave.fromPartial(object.roomLeave)
      : undefined;
    message.roomStart = (object.roomStart !== undefined && object.roomStart !== null)
      ? RoomStart.fromPartial(object.roomStart)
      : undefined;
    message.cmdSubmit = (object.cmdSubmit !== undefined && object.cmdSubmit !== null)
      ? CmdSubmit.fromPartial(object.cmdSubmit)
      : undefined;
    message.matchResult = (object.matchResult !== undefined && object.matchResult !== null)
      ? MatchResult.fromPartial(object.matchResult)
      : undefined;
    message.connResume = (object.connResume !== undefined && object.connResume !== null)
      ? ConnResume.fromPartial(object.connResume)
      : undefined;
    message.ping = (object.ping !== undefined && object.ping !== null) ? Ping.fromPartial(object.ping) : undefined;
    message.clientCaps = (object.clientCaps !== undefined && object.clientCaps !== null)
      ? ClientCaps.fromPartial(object.clientCaps)
      : undefined;
    message.judgeVerdict = (object.judgeVerdict !== undefined && object.judgeVerdict !== null)
      ? JudgeVerdict.fromPartial(object.judgeVerdict)
      : undefined;
    return message;
  },
};

function createBaseRoomState(): RoomState {
  return { code: "", players: [], phase: 0 };
}

export const RoomState: MessageFns<RoomState> = {
  encode(message: RoomState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    for (const v of message.players) {
      PlayerSlot.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.phase !== 0) {
      writer.uint32(24).int32(message.phase);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.players.push(PlayerSlot.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.phase = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RoomState>, I>>(base?: I): RoomState {
    return RoomState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomState>, I>>(object: I): RoomState {
    const message = createBaseRoomState();
    message.code = object.code ?? "";
    message.players = object.players?.map((e) => PlayerSlot.fromPartial(e)) || [];
    message.phase = object.phase ?? 0;
    return message;
  },
};

function createBaseMatchStart(): MatchStart {
  return { roomId: "", mode: 0, seed: 0, startFrame: 0, localSide: 0 };
}

export const MatchStart: MessageFns<MatchStart> = {
  encode(message: MatchStart, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomId !== "") {
      writer.uint32(10).string(message.roomId);
    }
    if (message.mode !== 0) {
      writer.uint32(16).int32(message.mode);
    }
    if (message.seed !== 0) {
      writer.uint32(24).uint64(message.seed);
    }
    if (message.startFrame !== 0) {
      writer.uint32(32).uint32(message.startFrame);
    }
    if (message.localSide !== 0) {
      writer.uint32(40).uint32(message.localSide);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchStart {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchStart();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.seed = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.startFrame = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.localSide = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MatchStart>, I>>(base?: I): MatchStart {
    return MatchStart.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchStart>, I>>(object: I): MatchStart {
    const message = createBaseMatchStart();
    message.roomId = object.roomId ?? "";
    message.mode = object.mode ?? 0;
    message.seed = object.seed ?? 0;
    message.startFrame = object.startFrame ?? 0;
    message.localSide = object.localSide ?? 0;
    return message;
  },
};

function createBaseConnResync(): ConnResync {
  return { seed: 0, startFrame: 0, log: [], curFrame: 0 };
}

export const ConnResync: MessageFns<ConnResync> = {
  encode(message: ConnResync, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seed !== 0) {
      writer.uint32(8).uint64(message.seed);
    }
    if (message.startFrame !== 0) {
      writer.uint32(16).uint32(message.startFrame);
    }
    for (const v of message.log) {
      FrameCmds.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.curFrame !== 0) {
      writer.uint32(32).uint32(message.curFrame);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnResync {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnResync();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seed = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.startFrame = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.log.push(FrameCmds.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.curFrame = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ConnResync>, I>>(base?: I): ConnResync {
    return ConnResync.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnResync>, I>>(object: I): ConnResync {
    const message = createBaseConnResync();
    message.seed = object.seed ?? 0;
    message.startFrame = object.startFrame ?? 0;
    message.log = object.log?.map((e) => FrameCmds.fromPartial(e)) || [];
    message.curFrame = object.curFrame ?? 0;
    return message;
  },
};

function createBaseMatchFound(): MatchFound {
  return { gameUrl: "", ticket: "" };
}

export const MatchFound: MessageFns<MatchFound> = {
  encode(message: MatchFound, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gameUrl !== "") {
      writer.uint32(10).string(message.gameUrl);
    }
    if (message.ticket !== "") {
      writer.uint32(18).string(message.ticket);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchFound {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchFound();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gameUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ticket = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MatchFound>, I>>(base?: I): MatchFound {
    return MatchFound.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchFound>, I>>(object: I): MatchFound {
    const message = createBaseMatchFound();
    message.gameUrl = object.gameUrl ?? "";
    message.ticket = object.ticket ?? "";
    return message;
  },
};

function createBasePeerDc(): PeerDc {
  return { side: 0, graceMs: 0 };
}

export const PeerDc: MessageFns<PeerDc> = {
  encode(message: PeerDc, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.side !== 0) {
      writer.uint32(8).uint32(message.side);
    }
    if (message.graceMs !== 0) {
      writer.uint32(16).uint32(message.graceMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PeerDc {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeerDc();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.side = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.graceMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PeerDc>, I>>(base?: I): PeerDc {
    return PeerDc.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerDc>, I>>(object: I): PeerDc {
    const message = createBasePeerDc();
    message.side = object.side ?? 0;
    message.graceMs = object.graceMs ?? 0;
    return message;
  },
};

function createBaseEloDelta(): EloDelta {
  return { delta: 0, after: 0, rankAfter: "" };
}

export const EloDelta: MessageFns<EloDelta> = {
  encode(message: EloDelta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.delta !== 0) {
      writer.uint32(8).int32(message.delta);
    }
    if (message.after !== 0) {
      writer.uint32(16).int32(message.after);
    }
    if (message.rankAfter !== "") {
      writer.uint32(26).string(message.rankAfter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EloDelta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEloDelta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.delta = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.after = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rankAfter = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EloDelta>, I>>(base?: I): EloDelta {
    return EloDelta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EloDelta>, I>>(object: I): EloDelta {
    const message = createBaseEloDelta();
    message.delta = object.delta ?? 0;
    message.after = object.after ?? 0;
    message.rankAfter = object.rankAfter ?? "";
    return message;
  },
};

function createBaseMatchOver(): MatchOver {
  return { winnerSide: 0, reason: "", mismatch: false, elo: undefined };
}

export const MatchOver: MessageFns<MatchOver> = {
  encode(message: MatchOver, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.winnerSide !== 0) {
      writer.uint32(8).uint32(message.winnerSide);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.mismatch !== false) {
      writer.uint32(24).bool(message.mismatch);
    }
    if (message.elo !== undefined) {
      EloDelta.encode(message.elo, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchOver {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchOver();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.winnerSide = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mismatch = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.elo = EloDelta.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MatchOver>, I>>(base?: I): MatchOver {
    return MatchOver.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchOver>, I>>(object: I): MatchOver {
    const message = createBaseMatchOver();
    message.winnerSide = object.winnerSide ?? 0;
    message.reason = object.reason ?? "";
    message.mismatch = object.mismatch ?? false;
    message.elo = (object.elo !== undefined && object.elo !== null) ? EloDelta.fromPartial(object.elo) : undefined;
    return message;
  },
};

function createBaseRoomError(): RoomError {
  return { code: "", message: "" };
}

export const RoomError: MessageFns<RoomError> = {
  encode(message: RoomError, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomError {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RoomError>, I>>(base?: I): RoomError {
    return RoomError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomError>, I>>(object: I): RoomError {
    const message = createBaseRoomError();
    message.code = object.code ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBasePong(): Pong {
  return {};
}

export const Pong: MessageFns<Pong> = {
  encode(_: Pong, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Pong {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePong();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Pong>, I>>(base?: I): Pong {
    return Pong.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Pong>, I>>(_: I): Pong {
    const message = createBasePong();
    return message;
  },
};

function createBaseJudgeRequest(): JudgeRequest {
  return { requestId: "", seed: 0, mode: 0, endFrame: 0, frames: [] };
}

export const JudgeRequest: MessageFns<JudgeRequest> = {
  encode(message: JudgeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.seed !== 0) {
      writer.uint32(16).uint64(message.seed);
    }
    if (message.mode !== 0) {
      writer.uint32(24).int32(message.mode);
    }
    if (message.endFrame !== 0) {
      writer.uint32(32).uint32(message.endFrame);
    }
    for (const v of message.frames) {
      FrameCmds.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JudgeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJudgeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.seed = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.endFrame = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.frames.push(FrameCmds.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JudgeRequest>, I>>(base?: I): JudgeRequest {
    return JudgeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JudgeRequest>, I>>(object: I): JudgeRequest {
    const message = createBaseJudgeRequest();
    message.requestId = object.requestId ?? "";
    message.seed = object.seed ?? 0;
    message.mode = object.mode ?? 0;
    message.endFrame = object.endFrame ?? 0;
    message.frames = object.frames?.map((e) => FrameCmds.fromPartial(e)) || [];
    return message;
  },
};

function createBaseServerMsg(): ServerMsg {
  return {
    roomState: undefined,
    matchStart: undefined,
    frameBatch: undefined,
    connResync: undefined,
    peerDc: undefined,
    matchOver: undefined,
    roomError: undefined,
    pong: undefined,
    matchFound: undefined,
    judgeRequest: undefined,
  };
}

export const ServerMsg: MessageFns<ServerMsg> = {
  encode(message: ServerMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomState !== undefined) {
      RoomState.encode(message.roomState, writer.uint32(10).fork()).join();
    }
    if (message.matchStart !== undefined) {
      MatchStart.encode(message.matchStart, writer.uint32(18).fork()).join();
    }
    if (message.frameBatch !== undefined) {
      FrameBatch.encode(message.frameBatch, writer.uint32(26).fork()).join();
    }
    if (message.connResync !== undefined) {
      ConnResync.encode(message.connResync, writer.uint32(34).fork()).join();
    }
    if (message.peerDc !== undefined) {
      PeerDc.encode(message.peerDc, writer.uint32(42).fork()).join();
    }
    if (message.matchOver !== undefined) {
      MatchOver.encode(message.matchOver, writer.uint32(50).fork()).join();
    }
    if (message.roomError !== undefined) {
      RoomError.encode(message.roomError, writer.uint32(58).fork()).join();
    }
    if (message.pong !== undefined) {
      Pong.encode(message.pong, writer.uint32(66).fork()).join();
    }
    if (message.matchFound !== undefined) {
      MatchFound.encode(message.matchFound, writer.uint32(74).fork()).join();
    }
    if (message.judgeRequest !== undefined) {
      JudgeRequest.encode(message.judgeRequest, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomState = RoomState.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.matchStart = MatchStart.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.frameBatch = FrameBatch.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.connResync = ConnResync.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.peerDc = PeerDc.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.matchOver = MatchOver.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.roomError = RoomError.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.pong = Pong.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.matchFound = MatchFound.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.judgeRequest = JudgeRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ServerMsg>, I>>(base?: I): ServerMsg {
    return ServerMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerMsg>, I>>(object: I): ServerMsg {
    const message = createBaseServerMsg();
    message.roomState = (object.roomState !== undefined && object.roomState !== null)
      ? RoomState.fromPartial(object.roomState)
      : undefined;
    message.matchStart = (object.matchStart !== undefined && object.matchStart !== null)
      ? MatchStart.fromPartial(object.matchStart)
      : undefined;
    message.frameBatch = (object.frameBatch !== undefined && object.frameBatch !== null)
      ? FrameBatch.fromPartial(object.frameBatch)
      : undefined;
    message.connResync = (object.connResync !== undefined && object.connResync !== null)
      ? ConnResync.fromPartial(object.connResync)
      : undefined;
    message.peerDc = (object.peerDc !== undefined && object.peerDc !== null)
      ? PeerDc.fromPartial(object.peerDc)
      : undefined;
    message.matchOver = (object.matchOver !== undefined && object.matchOver !== null)
      ? MatchOver.fromPartial(object.matchOver)
      : undefined;
    message.roomError = (object.roomError !== undefined && object.roomError !== null)
      ? RoomError.fromPartial(object.roomError)
      : undefined;
    message.pong = (object.pong !== undefined && object.pong !== null) ? Pong.fromPartial(object.pong) : undefined;
    message.matchFound = (object.matchFound !== undefined && object.matchFound !== null)
      ? MatchFound.fromPartial(object.matchFound)
      : undefined;
    message.judgeRequest = (object.judgeRequest !== undefined && object.judgeRequest !== null)
      ? JudgeRequest.fromPartial(object.judgeRequest)
      : undefined;
    return message;
  },
};

function createBaseEnvelope(): Envelope {
  return { client: undefined, server: undefined };
}

export const Envelope: MessageFns<Envelope> = {
  encode(message: Envelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.client !== undefined) {
      ClientMsg.encode(message.client, writer.uint32(10).fork()).join();
    }
    if (message.server !== undefined) {
      ServerMsg.encode(message.server, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Envelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.client = ClientMsg.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.server = ServerMsg.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Envelope>, I>>(base?: I): Envelope {
    return Envelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Envelope>, I>>(object: I): Envelope {
    const message = createBaseEnvelope();
    message.client = (object.client !== undefined && object.client !== null)
      ? ClientMsg.fromPartial(object.client)
      : undefined;
    message.server = (object.server !== undefined && object.server !== null)
      ? ServerMsg.fromPartial(object.server)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
