// 统一响应包络 + 错误码（SERVER_API.md §1.2 / §1.3）。

export type ApiResp<T> =
  | { ok: true; data: T }
  | { ok: false; error: { code: string; message: string } };

export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  REV_CONFLICT: 'REV_CONFLICT',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  DAILY_CAP_REACHED: 'DAILY_CAP_REACHED',
  INVALID_RECEIPT: 'INVALID_RECEIPT',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL: 'INTERNAL',
  // —— 账号系统（SA-1/SA-2）——
  LOGIN_ID_TAKEN: 'LOGIN_ID_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  ALREADY_BOUND: 'ALREADY_BOUND',
  OAUTH_FAILED: 'OAUTH_FAILED',
  // —— 社交系统（S6，SOCIAL_DESIGN §5）——
  FRIEND_CAP_REACHED: 'FRIEND_CAP_REACHED',
  ALREADY_FRIEND: 'ALREADY_FRIEND',
  NOT_FRIEND: 'NOT_FRIEND',
  BLOCKED: 'BLOCKED',
  ALREADY_CLAIMED: 'ALREADY_CLAIMED',
  NO_ATTACHMENT: 'NO_ATTACHMENT',
  // —— SLG 大世界（S8，SLG_DESIGN §14.7）——
  WORLD_FULL: 'WORLD_FULL',
  WORLD_CLOSED: 'WORLD_CLOSED',
  TILE_NOT_OWNED: 'TILE_NOT_OWNED',
  TILE_OCCUPIED: 'TILE_OCCUPIED',
  OUT_OF_RANGE: 'OUT_OF_RANGE',
  NO_TROOPS: 'NO_TROOPS',
  TROOP_CAP_REACHED: 'TROOP_CAP_REACHED',
  PROTECTED: 'PROTECTED',
  MARCH_NOT_FOUND: 'MARCH_NOT_FOUND',
  FAMILY_FULL: 'FAMILY_FULL',
  NOT_IN_FAMILY: 'NOT_IN_FAMILY',
  ALREADY_IN_FAMILY: 'ALREADY_IN_FAMILY',
  AUCTION_NOT_FOUND: 'AUCTION_NOT_FOUND',
  AUCTION_CLOSED: 'AUCTION_CLOSED',
  NOT_DESIGNATED_BUYER: 'NOT_DESIGNATED_BUYER',
  INSUFFICIENT_RESOURCES: 'INSUFFICIENT_RESOURCES',
  AUCTION_LIMIT_REACHED: 'AUCTION_LIMIT_REACHED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export function ok<T>(data: T): { ok: true; data: T } {
  return { ok: true, data };
}

export function err(code: ErrorCode, message: string): {
  ok: false;
  error: { code: string; message: string };
} {
  return { ok: false, error: { code, message } };
}

/** HTTP 状态码 → 错误码的约定映射（SERVER_API.md §2 标注的状态码）。 */
export const ERROR_HTTP_STATUS: Record<string, number> = {
  [ErrorCode.UNAUTHENTICATED]: 401,
  [ErrorCode.REV_CONFLICT]: 409,
  [ErrorCode.INSUFFICIENT_FUNDS]: 402,
  [ErrorCode.DAILY_CAP_REACHED]: 429,
  [ErrorCode.INVALID_RECEIPT]: 400,
  [ErrorCode.ROOM_NOT_FOUND]: 404,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.ROOM_FULL]: 409,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.NOT_IMPLEMENTED]: 501,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.INTERNAL]: 500,
  [ErrorCode.LOGIN_ID_TAKEN]: 409,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.WEAK_PASSWORD]: 400,
  [ErrorCode.ALREADY_BOUND]: 409,
  [ErrorCode.OAUTH_FAILED]: 400,
  [ErrorCode.FRIEND_CAP_REACHED]: 409,
  [ErrorCode.ALREADY_FRIEND]: 409,
  [ErrorCode.NOT_FRIEND]: 403,
  [ErrorCode.BLOCKED]: 403,
  [ErrorCode.ALREADY_CLAIMED]: 409,
  [ErrorCode.NO_ATTACHMENT]: 400,
  [ErrorCode.WORLD_FULL]: 409,
  [ErrorCode.WORLD_CLOSED]: 409,
  [ErrorCode.TILE_NOT_OWNED]: 403,
  [ErrorCode.TILE_OCCUPIED]: 409,
  [ErrorCode.OUT_OF_RANGE]: 400,
  [ErrorCode.NO_TROOPS]: 409,
  [ErrorCode.TROOP_CAP_REACHED]: 409,
  [ErrorCode.PROTECTED]: 403,
  [ErrorCode.MARCH_NOT_FOUND]: 404,
  [ErrorCode.FAMILY_FULL]: 409,
  [ErrorCode.NOT_IN_FAMILY]: 403,
  [ErrorCode.ALREADY_IN_FAMILY]: 409,
  [ErrorCode.AUCTION_NOT_FOUND]: 404,
  [ErrorCode.AUCTION_CLOSED]: 409,
  [ErrorCode.NOT_DESIGNATED_BUYER]: 403,
  [ErrorCode.INSUFFICIENT_RESOURCES]: 402,
  [ErrorCode.AUCTION_LIMIT_REACHED]: 409,
};
