// Save data and contract types. SaveData is the single authoritative root of the meta system (META_DESIGN.md §3.1).
// Mirrors the client at client/src/game/meta/SaveData.ts (S0-1); this file is the authoritative server copy
// and does not depend on client/src/game. The SaveData schema in openapi.yml derives from this.

export type Rarity = 'common' | 'rare' | 'epic' | 'legendary';

export interface LevelRecord {
  timeMs?: number;
  leaked?: number;
  [k: string]: unknown;
}

// ── Equipment instances (EQUIPMENT_DESIGN §3.1) ─────────────────────────────
// Catalog (defId → slot/rarity/material/recipe) is in equipment.ts; combat stats are in @nw/engine.
import type { EquipRarity, EquipSlot } from './equipment';
import type { RankId } from './ladder';
import type { BattlePassData } from './battlepass';
import type { RetentionSave } from './retention';

/** Affix (unified shape for primary/secondary/special affixes); id points to the affix pool, value is the rolled number. */
export interface Affix {
  id: string;
  value: number;
}

/** Equipment instance (server-authoritative; enhancement level / affixes / rarity stored with the item). */
export interface EquipmentInstance {
  id: string; // instance id (generated by the server)
  defId: string; // equipment definition id (determines base stats/slot/material; see equipment.ts)
  rarity: EquipRarity; // denormalized cache of defId's rarity, for sorting/querying
  level: number; // enhancement level 0..9
  affixes: Affix[]; // affixes (can be rerolled via refinement)
  locked?: boolean; // prevents accidental use as enhancement fuel
}

/** Slot → instance id mapping for a single loadout. */
export type GearSlotMap = Partial<Record<EquipSlot, string /* instanceId */>>;

/** Gear loadout: phase one uses a global shared loadout for all units; byUnit is reserved for per-unit-type loadouts (EQUIPMENT_DESIGN §3.1/§3.2). */
export interface GearLoadout {
  global?: GearSlotMap;
  byUnit?: Record<string /* unitType */, GearSlotMap>;
}

export interface SaveData {
  version: number;
  accountId: string;
  rev: number;
  updatedAt: number;

  // —— Server-authoritative section (client read-only, §2) ——
  // wallet/gacha: from S5 onward these are read-only mirrors of the commercial service's authority
  // (meta fills them in after receiving an economy operation receipt).
  wallet: { coins: number };
  inventory: {
    skins: string[];
    items: Record<string, number>;
  };
  gacha: { pity: Record<string, number> };
  // Fulfilled purchase orders (commercial orderId). Idempotent delivery ledger: redelivery uses $addToSet + $ne guard for deduplication (S5-5).
  deliveredOrders: string[];
  pvp: {
    elo: number;
    rank: string;
    wins: number;
    losses: number;
    streak: number;
    // —— S11 season fields (SEASON_DESIGN §4) ——
    /** Season number this pvp data belongs to; if behind the clock's current season, triggers lazy migration. */
    seasonNo: number;
    /** Highest ELO reached this season (tracked with max at each match settlement). */
    seasonPeakElo: number;
    /** Peak rank this season (derived from seasonPeakElo; TITLE_DESIGN season settlement reads this to award titles). */
    seasonPeakRank: RankId;
    /** Rank ids ever first-reached historically (lifetime ledger; idempotent guard for first-reach coin reward; not reset across seasons). */
    reachedRanks: RankId[];
  };

  // —— Stamina (A4). Server-authoritative, deducted in real time; natural regen 1 point/6 min, cap 120. Absent in old saves = treated as full. ——
  // regenAt = timestamp (ms) of the next +1 regen tick; 0 when already at cap (no timer needed).
  stamina?: { current: number; regenAt: number };

  // —— Titles (S10, TITLE_DESIGN §2). Server-authoritative; not writable via PUT /save. Absent = treated as empty set, lazily created. ——
  // Written by season settlement / achievement claim / admin grant; equipped['title'] is the equipped slot (client sync section).
  titles?: string[];

  // —— Battle pass (S11-C, SEASON_DESIGN §C). Server-authoritative; not writable via PUT /save. Absent = treated as not enrolled, lazily created. ——
  battlePass?: BattlePassData;

  // —— Retention system (B5, RETENTION_DESIGN). Server-authoritative; not writable via PUT /save. Lazily created. ——
  retention?: RetentionSave;

  // —— Achievement system (server-authoritative, ACHIEVEMENT_DESIGN §3). Lazily created to save storage; absent = treated as all-zero/empty. ——
  // Counters are written only at authoritative PvE/PvP settlement points (A2); the PUT /save allowlist
  // only accepts equipped/flags, so these three sections are structurally dropped (even if the client sends them they are never persisted) — no extra guard needed.
  stats?: Record<string, number>; // lifetime cumulative stats (StatKey → value), monotonically increasing
  achievements?: Record<string, { claimedTiers: number[] }>; // achId → subset of claimed tier numbers ⊆ [1,2,3]
  antiCheat?: {
    // PvP stat anti-cheat (§4.4), server-authoritative, client read-only or not sent at all
    statSuspicion: number; // accumulated cheat-hit count → determines inspection tier
    lastFlaggedTs?: number;
    // PvE anti-cheat (S4-4): count of replay recalculation mismatches; ban (pveBanned) on threshold.
    pveRejectCount?: number;
    pveBanned?: boolean;
  };

  // —— Client sync section (light validation, §2) ——
  progress: {
    cleared: string[];
    stars: Record<string, 1 | 2 | 3>;
    best: Record<string, LevelRecord>;
  };
  materials: Record<string, number>;
  /**
   * @deprecated Per-stat material upgrades from S3-2 (inf_hp/inf_dmg…). From S12 onward, unit progression
   * switches to a single level + card collection system (see unitLevels / cardInventory); the engine no longer
   * reads this field for progression. Kept for old-save compatibility; will be retired after S12 cleanup.
   */
  pveUpgrades: Record<string, number>;
  // —— Unit progression (S12, ECONOMY_NUMBERS §4 / ADR-009). Server-authoritative; not writable via PUT /save. ——
  /** Unit power level (unitId → 1..9) = highest owned card tier per unit type, derived from cardInventory (deriveUnitLevels). The engine reads this to apply blueprints. */
  unitLevels: Record<string, number>;
  /** Unit card inventory: `${unitId}:${level}` → count. The raw source for card collection synthesis (5 → 1). */
  cardInventory: Record<string, number>;
  /** Equipped cosmetics (slot → skinId). Purely visual, no combat effect, so still uploaded via the PUT /save sync section. */
  equipped: Record<string, string>;
  flags: Record<string, boolean>;

  // —— Equipment system (server-authoritative, EQUIPMENT_DESIGN §3.1). Not writable via PUT /save; only /equipment/* endpoints write. ——
  // Note: deliberately does not reuse the cosmetic `equipped` field (which already carries skin selection);
  // equipment loadout is stored separately in `gear`.
  // Absent in old saves → treated as empty; all read sites use `?? {}` as fallback (no migration runner, lazy defaults).
  equipmentInv: Record<string, EquipmentInstance>; // instanceId → instance
  gear: GearLoadout; // equipped loadout
}

/**
 * Client sync fields accepted by PUT /save (SERVER_API.md §2.2).
 * From PVE_INTEGRITY_PLAN §8 onward, progress/materials/pveUpgrades are promoted to server-authoritative
 * (written only by /pve/* + ranked settlement), narrowing PUT /save to equipped/flags only.
 */
export type SyncPatch = Partial<Pick<SaveData, 'equipped' | 'flags'>>;

// v2 (2026-06-21): Added equipmentInv + gear (equipment system E0). Additive fields only; does not touch equipped.
// Old saves lazily default via `?? {}` at read sites; no destructive migration.
// v3 (2026-06-21): Unit progression rework (S12) — added unitLevels + cardInventory; pveUpgrades marked deprecated.
// Additive fields only; old saves lazily default to empty (game not yet live, no real saves; progression restarts from L1; no pveUpgrades→unitLevels conversion).
export const SAVE_VERSION = 3;

/** Default save data for a new account. All authoritative sections start from zero. */
export function makeNewSave(accountId: string, now: number): SaveData {
  return {
    version: SAVE_VERSION,
    accountId,
    rev: 0,
    updatedAt: now,
    wallet: { coins: 0 },
    inventory: { skins: [], items: {} },
    gacha: { pity: {} },
    deliveredOrders: [],
    pvp: {
      elo: 1000,
      rank: 'unranked',
      wins: 0,
      losses: 0,
      streak: 0,
      seasonNo: 1,
      seasonPeakElo: 1000,
      seasonPeakRank: 'bronze' as RankId,
      reachedRanks: [],
    },
    progress: { cleared: [], stars: {}, best: {} },
    materials: {},
    pveUpgrades: {},
    unitLevels: {},
    cardInventory: {},
    equipped: {},
    flags: {},
    equipmentInv: {},
    gear: {},
  };
}
