// transport.proto encode/decode layer (M12, ADR-023 P3). Single source of truth =
// ../../../contracts/transport.proto, generated by ts-proto (build-time type safety).
//
// Public API: decode ClientMsg (discriminated union) + construct and encode ServerMsg.
import {
  Envelope,
  ServerMsg as ProtoServerMsg,
} from '../generated/transport';

// ── Enum constants ────────────────────────────────────────────────────────────
export const RoomPhase = {
  WAITING: 0,
  READY: 1,
  COUNTDOWN: 2,
  IN_MATCH: 3,
  OVER: 4,
} as const;
export type RoomPhaseVal = (typeof RoomPhase)[keyof typeof RoomPhase];

export const MatchMode = {
  FRIENDLY: 0,
  RANKED: 1,
} as const;
export type MatchModeVal = (typeof MatchMode)[keyof typeof MatchMode];

// ── Pass-through payload shapes (server side) ─────────────────────────────────
export interface SideCmd {
  side: number;
  commands: Uint8Array;
}
export interface FrameCmds {
  frame: number;
  cmds: SideCmd[];
}

// ── ClientMsg discriminated union (by oneof case) ────────────────────────────
export type ClientMsg =
  | { case: 'room_create'; mode: number }
  | { case: 'room_join'; code: string }
  | { case: 'room_ready'; ready: boolean }
  | { case: 'room_leave' }
  | { case: 'room_start' }
  | { case: 'cmd_submit'; commands: Uint8Array }
  | { case: 'match_result'; stateHash: string; winnerSide: number; stats?: Record<string, number> }
  | { case: 'conn_resume'; roomId: string; lastFrame: number }
  | { case: 'ping' }
  | { case: 'unknown' };

// ── ServerMsg construction parameters (by oneof case) ────────────────────────
export interface PlayerSlotOut {
  side: number;
  name: string;
  ready: boolean;
  connected: boolean;
}
export type ServerMsg =
  | { case: 'room_state'; code: string; players: PlayerSlotOut[]; phase: number }
  | {
      case: 'match_start';
      roomId: string;
      mode: number;
      seed: number;
      startFrame: number;
      localSide: number;
      opponentName: string;
      opponentPublicId: string;
      opponentTitle?: string;
      topDeck?: string[];
      bottomDeck?: string[];
    }
  | { case: 'frame_batch'; toFrame: number; frames: FrameCmds[] }
  | {
      case: 'conn_resync';
      seed: number;
      startFrame: number;
      log: FrameCmds[];
      curFrame: number;
    }
  | { case: 'peer_dc'; side: number; graceMs: number }
  | {
      case: 'match_over';
      winnerSide: number;
      reason: string;
      mismatch: boolean;
      elo?: { delta: number; after: number; rankAfter: string };
    }
  | { case: 'room_error'; code: string; message: string }
  | { case: 'pong' };

function parseStatsJson(raw: unknown): Record<string, number> | undefined {
  if (typeof raw !== 'string' || raw.length === 0) return undefined;
  try {
    const obj = JSON.parse(raw) as unknown;
    if (!obj || typeof obj !== 'object' || Array.isArray(obj)) return undefined;
    const out: Record<string, number> = {};
    for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
      if (typeof v === 'number' && Number.isFinite(v)) out[k] = v;
    }
    return Object.keys(out).length > 0 ? out : undefined;
  } catch {
    return undefined;
  }
}

export function decodeClient(buf: Uint8Array): ClientMsg {
  const env = Envelope.decode(buf);
  const client = env.client;
  if (!client) return { case: 'unknown' };

  if (client.roomCreate) return { case: 'room_create', mode: client.roomCreate.mode };
  if (client.roomJoin) return { case: 'room_join', code: client.roomJoin.code };
  if (client.roomReady) return { case: 'room_ready', ready: client.roomReady.ready };
  if (client.roomLeave !== undefined) return { case: 'room_leave' };
  if (client.roomStart !== undefined) return { case: 'room_start' };
  if (client.cmdSubmit) return { case: 'cmd_submit', commands: client.cmdSubmit.commands };
  if (client.matchResult) {
    return {
      case: 'match_result',
      stateHash: client.matchResult.stateHash,
      winnerSide: client.matchResult.winnerSide,
      stats: parseStatsJson(client.matchResult.statsJson),
    };
  }
  if (client.connResume) return { case: 'conn_resume', roomId: client.connResume.roomId, lastFrame: client.connResume.lastFrame };
  if (client.ping !== undefined) return { case: 'ping' };
  return { case: 'unknown' };
}

function framesToWire(frames: FrameCmds[]) {
  return frames.map((f) => ({
    frame: f.frame,
    cmds: f.cmds.map((s) => ({ side: s.side, commands: s.commands })),
  }));
}

export function encodeServer(msg: ServerMsg): Uint8Array {
  let server: ProtoServerMsg;
  switch (msg.case) {
    case 'room_state':
      server = {
        roomState: {
          code: msg.code,
          players: msg.players.map((p) => ({ side: p.side, name: p.name, ready: p.ready, connected: p.connected, publicId: '' })),
          phase: msg.phase,
        },
      };
      break;
    case 'match_start':
      server = {
        matchStart: {
          roomId: msg.roomId,
          mode: msg.mode,
          seed: msg.seed,
          startFrame: msg.startFrame,
          localSide: msg.localSide,
          opponentName: msg.opponentName,
          opponentPublicId: msg.opponentPublicId,
          opponentTitle: msg.opponentTitle ?? '',
          topDeck: msg.topDeck ?? [],
          bottomDeck: msg.bottomDeck ?? [],
        },
      };
      break;
    case 'frame_batch':
      server = { frameBatch: { toFrame: msg.toFrame, frames: framesToWire(msg.frames) } };
      break;
    case 'conn_resync':
      server = { connResync: { seed: msg.seed, startFrame: msg.startFrame, log: framesToWire(msg.log), curFrame: msg.curFrame } };
      break;
    case 'peer_dc':
      server = { peerDc: { side: msg.side, graceMs: msg.graceMs } };
      break;
    case 'match_over':
      server = {
        matchOver: {
          winnerSide: msg.winnerSide,
          reason: msg.reason,
          mismatch: msg.mismatch,
          elo: msg.elo ? { delta: msg.elo.delta, after: msg.elo.after, rankAfter: msg.elo.rankAfter } : undefined,
        },
      };
      break;
    case 'room_error':
      server = { roomError: { code: msg.code, message: msg.message } };
      break;
    case 'pong':
      server = { pong: {} };
      break;
  }
  return Envelope.encode(Envelope.fromPartial({ server })).finish();
}
