// Gameserver WebSocket client (S1-6): connection / reconnection / protocol encode-decode.
// Platform socket is provided by IPlatform.connectSocket (Web/CrazyGames=WebSocket, WeChat=wx).
// Protocol uses ts-proto codecs generated by C-2 (src/net/proto/transport.ts).
//
// Responsibility boundary: this class only manages the "reliable bidirectional message pipe".
// Lockstep playback (consuming frame_batch, advancing engine, buffering) lives in NetInputSource (S1-7);
// room UI lives in RoomScene (S1-8).
// After reconnection, only notifies the upper layer (onReconnect); the upper layer decides to send conn_resume to resume the match (S1-4).
import type { IGameSocket, IPlatform, SocketHandlers } from '../platform/IPlatform';
import { Envelope, type ClientMsg, type MatchMode, type ServerMsg } from './proto/transport';
import { netLog, type NetLogger } from './log';

export type NetState = 'idle' | 'connecting' | 'open' | 'reconnecting' | 'closed';

export interface NetClientHandlers {
  /** Called when a server message is received (already decoded from oneof). */
  onServerMsg(msg: ServerMsg): void;
  /** Called on connection state change (for UI notifications). */
  onStateChange?(state: NetState): void;
  /** Called when reconnection succeeds (socket re-opened, not the initial connection). Upper layer should send conn_resume. */
  onReconnect?(): void;
}

export interface NetClientOptions {
  /** WebSocket endpoint (without query string). gateway control plane = /gw; game data plane = match_found.game_url. */
  url: string;
  /**
   * Fetches a fresh credential (called on every connect/reconnect). gateway uses JWT (?token=); game uses ticket (?ticket=).
   * Reconnects reuse the same ticket (ticket exp only constrains the initial connection; game verifier accepts expired tickets for already-active rooms).
   */
  tokenProvider: () => Promise<string>;
  /** Handshake query parameter name: gateway = 'token' (default), game data plane = 'ticket'. */
  queryParam?: string;
  handlers: NetClientHandlers;
  /** Reconnect backoff delays (ms); capped at the last value once exhausted. Default [500,1000,2000,4000,8000]. */
  backoffMs?: number[];
  /** Application-layer heartbeat interval (ms); keeps the connection alive and produces visible traffic for the server. Default 25000; 0 = disabled. */
  pingIntervalMs?: number;
  /** Log tag (distinguishes the gateway / game connections). Default 'ws'. */
  tag?: string;
}

const DEFAULT_BACKOFF = [500, 1000, 2000, 4000, 8000];

export class NetClient {
  private socket: IGameSocket | null = null;
  private state: NetState = 'idle';
  /** Connection generation counter: incremented on every connect/disconnect to discard stale callbacks from old sockets (WeChat sockets cannot detach callbacks). */
  private gen = 0;
  private intentional = false; // intentional disconnect — do not reconnect
  private everOpened = false; // distinguishes the first open from a reconnect open
  private attempt = 0;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  private pingTimer: ReturnType<typeof setInterval> | null = null;
  private readonly backoff: number[];
  private readonly pingIntervalMs: number;
  private readonly log: NetLogger;

  constructor(
    private readonly platform: IPlatform,
    private readonly opt: NetClientOptions,
  ) {
    this.backoff = opt.backoffMs ?? DEFAULT_BACKOFF;
    this.pingIntervalMs = opt.pingIntervalMs ?? 25_000;
    this.log = netLog(opt.tag ?? 'ws');
  }

  getState(): NetState {
    return this.state;
  }

  /** Establish a connection (idempotent: ignored if already connected or connecting). */
  connect(): void {
    if (this.state === 'connecting' || this.state === 'open') return;
    this.intentional = false;
    this.attempt = 0;
    this.everOpened = false;
    void this.openSocket();
  }

  /** Intentionally disconnect (does not trigger reconnection). */
  disconnect(): void {
    this.intentional = true;
    this.gen++; // invalidate all callbacks from the current socket
    this.clearTimers();
    if (this.socket) {
      this.socket.close();
      this.socket = null;
    }
    this.setState('closed');
  }

  // ── Send (only in open state; dropped when not connected — upper layer should not issue commands while disconnected) ──────────
  createRoom(mode: MatchMode, deck: string[] = []): void {
    this.sendClient({ roomCreate: { mode, deck } });
  }
  joinRoom(code: string): void {
    this.sendClient({ roomJoin: { code } });
  }
  setReady(ready: boolean): void {
    this.sendClient({ roomReady: { ready } });
  }
  startMatch(): void {
    this.sendClient({ roomStart: {} });
  }
  leaveRoom(): void {
    this.sendClient({ roomLeave: {} });
  }
  /** Submit a play command (PlayerCommands bytes already encoded with game.proto, opaque). */
  submitCmd(commands: Uint8Array): void {
    this.sendClient({ cmdSubmit: { commands } });
  }
  reportResult(stateHash: string, winnerSide: number, stats?: Record<string, number>): void {
    // S9-6: attach this side's per-match achievement count JSON (only meaningful in ranked; meta accumulates after L1 validation; ignored in friendly).
    const statsJson = stats && Object.keys(stats).length > 0 ? JSON.stringify(stats) : '';
    this.sendClient({ matchResult: { stateHash, winnerSide, statsJson } });
  }
  /** Resume match after reconnection (call after onReconnect fires). */
  resume(roomId: string, lastFrame: number): void {
    this.sendClient({ connResume: { roomId, lastFrame } });
  }
  /** Report whether this client can serve as a headless re-computation judge (send after connecting to gateway, Phase C). */
  sendClientCaps(canJudge: boolean): void {
    this.sendClient({ clientCaps: { canJudge } });
  }
  /** Report the judge re-computation result (send after processing a judge_request, Phase C; PvE spot-checks include stars + achievement count statsJson). */
  sendJudgeVerdict(
    requestId: string,
    stateHash: string,
    winnerSide: number,
    ok: boolean,
    stars = 0,
    statsJson = '',
  ): void {
    this.sendClient({ judgeVerdict: { requestId, stateHash, winnerSide, ok, stars, statsJson } });
  }
  ping(): void {
    this.sendClient({ ping: {} });
  }

  // ───────────────────────── Internal ─────────────────────────

  private async openSocket(): Promise<void> {
    const gen = this.gen;
    this.setState(this.everOpened ? 'reconnecting' : 'connecting');
    let token: string;
    try {
      token = await this.opt.tokenProvider();
    } catch (e) {
      if (gen !== this.gen) return; // disconnected/reset in the meantime
      this.log.error('token fetch failed; will retry', e);
      this.scheduleReconnect();
      return;
    }
    if (gen !== this.gen) return;

    const url = `${this.opt.url}?${this.opt.queryParam ?? 'token'}=${encodeURIComponent(token)}`;
    this.log.info('opening socket', { url: this.opt.url });
    const handlers: SocketHandlers = {
      onOpen: () => {
        if (gen !== this.gen) return;
        this.attempt = 0;
        this.setState('open');
        this.startPing();
        if (this.everOpened) {
          this.log.info('reconnected');
          this.opt.handlers.onReconnect?.();
        }
        this.everOpened = true;
      },
      onMessage: (data) => {
        if (gen !== this.gen) return;
        let env: Envelope;
        try {
          env = Envelope.decode(data);
        } catch (e) {
          this.log.warn('dropped undecodable frame', e);
          return; // malformed frame dropped
        }
        if (env.server) this.opt.handlers.onServerMsg(env.server);
      },
      onClose: (code) => {
        if (gen !== this.gen || this.intentional) return;
        this.stopPing();
        this.socket = null;
        // 4409 'replaced': the server evicted us because another live session (another
        // tab/device) took over this account. Reconnecting would evict that session and
        // start an infinite ping-pong war — so give up instead of reconnecting.
        if (code === 4409) {
          this.log.warn('socket closed: replaced by another session; not reconnecting');
          this.setState('closed');
          return;
        }
        this.log.warn('socket closed', { code });
        this.scheduleReconnect();
      },
      onError: () => {
        // Browser: error is always followed by close; WeChat: may only fire error. Reconnection is uniformly driven by close.
        // If close never fires (very rare), a missed heartbeat is not fatal (upper layer pauses within its grace period).
        this.log.error('socket error', { url: this.opt.url });
      },
    };
    this.socket = this.platform.connectSocket(url, handlers);
  }

  private scheduleReconnect(): void {
    if (this.intentional) return;
    this.setState('reconnecting');
    const delay = this.backoff[Math.min(this.attempt, this.backoff.length - 1)]!;
    this.attempt++;
    this.clearReconnect();
    this.reconnectTimer = setTimeout(() => void this.openSocket(), delay);
  }

  private sendClient(client: ClientMsg): void {
    const kind = Object.keys(client)[0] ?? 'unknown';
    if (!this.socket || this.state !== 'open') {
      // Dropping ping while not connected is expected; dropping other commands warrants a warning (e.g. createRanked sent before socket opens would be silently lost).
      if (kind !== 'ping') this.log.warn(`send dropped (not open): ${kind}`, { state: this.state });
      return;
    }
    if (kind !== 'ping') this.log.info(`send ${kind}`);
    const bytes = Envelope.encode(Envelope.fromPartial({ client })).finish();
    this.socket.send(bytes);
  }

  private setState(s: NetState): void {
    if (this.state === s) return;
    this.state = s;
    this.log.info(`state ${s}`);
    this.opt.handlers.onStateChange?.(s);
  }

  private startPing(): void {
    if (this.pingIntervalMs <= 0) return;
    this.stopPing();
    this.pingTimer = setInterval(() => this.ping(), this.pingIntervalMs);
  }
  private stopPing(): void {
    if (this.pingTimer) {
      clearInterval(this.pingTimer);
      this.pingTimer = null;
    }
  }
  private clearReconnect(): void {
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
  }
  private clearTimers(): void {
    this.clearReconnect();
    this.stopPing();
  }
}
