/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/world/active-season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current active SLG season number (§20.8). Public endpoint — no auth required. */
        get: operations["getActiveSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/map/sparse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldMapSparse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/tile/{tileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Join the world; the system automatically places the player's base (§3.4: priority order: near family → outer-ring starter area → fallback). The player does not submit coordinates; the spawn location is determined by the server. */
        post: operations["joinWorld"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/occupy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["occupyTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abandonTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/relocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual base relocation (spend RELOCATE_COST coins to move the main base to (x,y), all territories are retained) */
        post: operations["relocateBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/watchtower": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a watchtower (spend WATCHTOWER_COST resources on own territory to create a large-radius persistent vision source; §18 G5 V2) */
        post: operations["buildWatchtower"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/march": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarches"];
        put?: never;
        post: operations["startMarch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/march/{marchId}/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recallMarch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sweepTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/troops/distribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CC-3 — distribute troops from baseTroopStock to card slots */
        post: operations["distributeTroops"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/troops/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CC-3 — recover an injured card by spending coins */
        post: operations["recoverCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/troops/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trainTroops"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/troops/speedup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["speedupTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/build/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Enqueue a home-city building upgrade (SLG_CITY_DESIGN P1). Deducts season resources up-front; the level is applied when the build completes. */
        post: operations["upgradeBuilding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/build/speedup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Spend coins to speed up the home-city build queue (SLG_CITY_DESIGN §6). */
        post: operations["speedupBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/defense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefense"];
        put: operations["setDefense"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeams"];
        put: operations["setTeams"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/siege/{siegeId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSiegeReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/nations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/nations/{capitalIdx}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setNationName"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/shop/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSlgShopItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/shop/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buySlgShopItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/{auctionId}/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buyAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/{auctionId}/bid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place a bid (saleMode='auction', B). amount = bid unit price; escrowed coins = amount × qty. */
        post: operations["placeBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/{auctionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/{sectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/dissolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dissolveSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/ally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["allySect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/unally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unallySect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/vote-remove-leader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["voteRemoveSectLeader"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendSectMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSectChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorldTileView: {
            x: number;
            y: number;
            /** @enum {string} */
            type: "neutral" | "resource" | "territory" | "familyKeep" | "center" | "base" | "obstacle" | "gate" | "stronghold";
            level: number;
            /** @enum {string} */
            resType?: "ink" | "paper" | "graphite" | "metal" | "sticker";
            occupied?: boolean;
            mine?: boolean;
            /** @description Occupier's 9-digit public id (populated when meta service is available) */
            ownerPublicId?: string;
            /** @description Occupier's display name (populated when meta service is available) */
            ownerName?: string;
            familyId?: string;
            garrison?: number;
            protectedUntil?: number;
            /** @description §18 G5 V2：A watchtower has been built on this tile (large-radius persistent vision source). The client renders the tower marker. */
            watchtower?: boolean;
            /** @description G5 vision: whether this tile is within the requester's current field of view. true = dynamic layer returned as-is; false = outside vision range, only the procedurally-generated base terrain is returned (all dynamic-layer data hidden, including the "occupied" signal). Populated only for /world/map viewport reads. */
            visible?: boolean;
            /** @description G5: this tile is owned by a family ally (within vision, not self). Client renders with friendly colour. */
            ally?: boolean;
            /** @description G5: this tile is owned by a member of an allied sect of the player's own sect (within vision, not self, not family). Alliances do not share vision; only distinguished on the map with a yellow border (§8.2, attacking/capturing between allies is forbidden). */
            allySect?: boolean;
        };
        WorldMapView: {
            worldId: string;
            cx: number;
            cy: number;
            r: number;
            tiles: components["schemas"]["WorldTileView"][];
        };
        /** @description Sparse occupied-tile view (zoom 2/3 bird's-eye layer). Contains only occupied tiles; unoccupied tiles are rendered locally by the client from proceduralTile. No profile RPC, no vision calculation. */
        WorldTileSparseView: {
            x: number;
            y: number;
            /** @enum {string} */
            type: "neutral" | "resource" | "territory" | "familyKeep" | "center" | "base" | "obstacle" | "gate" | "stronghold";
            mine?: boolean;
            /** @description lod=mid: same-family ally */
            ally?: boolean;
            /** @description lod=mid: allied sect member (not family) */
            allySect?: boolean;
        };
        WorldMapSparseView: {
            worldId: string;
            cx: number;
            cy: number;
            r: number;
            /** @enum {string} */
            lod: "thin" | "mid";
            /** @description Occupied tiles only, sparse array */
            tiles: components["schemas"]["WorldTileSparseView"][];
        };
        PlayerWorldView: {
            joined: boolean;
            /** @description The shard worldId the player belongs to (G6/§20: returned from join-season resolution; the client uses this to enter the world) */
            worldId?: string;
            troops?: number;
            troopCap?: number;
            resources?: {
                [key: string]: number;
            };
            yieldRate?: {
                [key: string]: number;
            };
            mainBaseTile?: string;
            familyId?: string;
            territoryCount?: number;
            /** @description Training queue (S8-2, ordered by completeAt ascending). The client uses this to render the queue countdown (C4). */
            trainingQueue?: {
                qty: number;
                /** Format: int64 */
                startAt: number;
                /** Format: int64 */
                completeAt: number;
            }[];
            /** @description Home-city building levels (SLG_CITY_DESIGN P1; desk≥1, others≥0 when present). Keys are BuildingKey values. */
            buildings?: {
                [key: string]: number;
            };
            /** @description Build queue (SLG_CITY_DESIGN §4, ordered by completeAt ascending). The client CityScene renders countdowns from this. */
            buildQueue?: {
                key: components["schemas"]["BuildingKey"];
                toLevel: number;
                /** Format: int64 */
                startAt: number;
                /** Format: int64 */
                completeAt: number;
            }[];
            /** @description Map of cardInstanceId → CardSLGState (troops, injury, teamId) */
            cardState?: {
                [key: string]: components["schemas"]["CardSLGState"];
            };
            /** @description Troops in the base pool available to distribute to card slots */
            baseTroopStock?: number;
        };
        /**
         * @description Home-city building identifier (SLG_CITY_DESIGN). P1 buildable: desk/inkPot/paperTray/graphiteMill/metalForge/stickerShop/cabinet/drillYard; wall/academy are P2.
         * @enum {string}
         */
        BuildingKey: "desk" | "inkPot" | "paperTray" | "graphiteMill" | "metalForge" | "stickerShop" | "cabinet" | "drillYard" | "wall" | "academy";
        MarchView: {
            marchId: string;
            /** @enum {string} */
            kind: "attack" | "reinforce" | "occupy" | "sweep" | "scout" | "return";
            fromTile: string;
            toTile: string;
            troops: number;
            departAt: number;
            arriveAt: number;
            /** @enum {string} */
            status: "marching" | "returning" | "arrived";
            /** @description G5: whether this march belongs to the requester (false = enemy march within vision range) */
            mine?: boolean;
        };
        AuctionView: {
            auctionId: string;
            worldId: string;
            sellerId: string;
            sellerName?: string;
            /**
             * @description CC-5: card = character card instance (qty always 1, gear must be empty before listing)
             * @enum {string}
             */
            itemType: "material" | "equipment" | "card";
            item: {
                [key: string]: unknown;
            };
            qty: number;
            /** @description Current effective unit price (fixed-price = sale unit price; auction = current highest bid unit price, or the starting price if no bids placed) */
            price: number;
            /** @description Current effective unit price × qty */
            totalPrice?: number;
            /** @enum {string} */
            currency?: "coins";
            /** @enum {string} */
            status: "open" | "sold" | "cancelled" | "expired";
            expireAt: number;
            designatedBuyerId?: string;
            taxPaid?: number;
            buyerId?: string;
            /** @enum {string} */
            saleMode: "fixed" | "auction";
            /** @description Auction starting unit price */
            startPrice?: number;
            /** @description Auction buyout unit price floor (optional) */
            buyoutPrice?: number;
            /** @description Current highest bid (unit price; coins are held in escrow) */
            topBid?: {
                bidderId: string;
                amount: number;
                ts: number;
            };
        };
        SectView: {
            sectId: string;
            worldId: string;
            name: string;
            tag: string;
            leaderFamilyId: string;
            leaderId: string;
            memberFamilyCount: number;
            allySectIds: string[];
            prosperity: number;
        };
        SectMemberFamilyView: {
            familyId: string;
            name: string;
            tag: string;
            leaderId: string;
            memberCount: number;
            territoryCount: number;
        };
        SectDetailView: components["schemas"]["SectView"] & {
            memberFamilies: components["schemas"]["SectMemberFamilyView"][];
            removalVote?: {
                nomineeFamilyId: string;
                voteCount: number;
                needed: number;
            };
        };
        SectMessageView: {
            id: string;
            senderId: string;
            senderName: string;
            body: string;
            ts: number;
        };
        SectVoteResult: {
            passed: boolean;
            voteCount: number;
            needed: number;
        };
        NationView: {
            /** @description 0~9, index into CAPITAL_FRACTIONS */
            capitalIdx: number;
            x: number;
            y: number;
            ownerId?: string;
            familyId?: string;
            nationName?: string;
            foundedAt?: number;
        };
        SeasonView: {
            worldId: string;
            season: number;
            shard: number;
            /** @enum {string} */
            status: "open" | "active" | "settling" | "closed";
            openAt: number;
            resetAt?: number;
            capacity: number;
            population: number;
            mapW: number;
            mapH: number;
        };
        SlgShopItemView: {
            id: string;
            /** @description Price in coins */
            cost: number;
            /** @enum {string} */
            kind: "troop_speedup" | "resource_pack" | "protection" | "battle_pass";
            effect: {
                [key: string]: unknown;
            };
            description: string;
        };
        SiegeReplayView: {
            siegeId: string;
            seed: number;
            /** @enum {string} */
            outcome: "attacker_win" | "defender_win" | "draw";
            level: {
                [key: string]: unknown;
            };
        };
        CardSLGState: {
            /** @description Troops currently allocated to this card */
            currentTroops: number;
            /** @description Unix ms timestamp when injury ends; null = not injured */
            injuredUntil?: number | null;
            /** @description Team this card is assigned to */
            teamId?: string | null;
        };
        ArmyEntry: {
            /** @description CC-3 primary key (character card instance) */
            cardInstanceId?: string;
            /** @description Legacy unit type (synthesis/replay paths only) */
            unitType?: string;
            col: number;
            row: number;
            /** @description Legacy initial HP for replay data */
            initialHp?: number;
        };
        TeamTemplate: {
            id: string;
            name: string;
            army: components["schemas"]["ArmyEntry"][];
        };
        DefenseConfig: {
            [key: string]: unknown;
        };
        OkResponse: {
            /** @enum {boolean} */
            ok: true;
        };
        MarchIdResponse: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getActiveSeason: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active season */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            /** @description Current active SLG world season number */
                            season: number;
                        };
                    };
                };
            };
        };
    };
    getWorldMap: {
        parameters: {
            query: {
                worldId: string;
                cx: number;
                cy: number;
                r: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map viewport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldMapView"];
                    };
                };
            };
        };
    };
    getWorldMapSparse: {
        parameters: {
            query: {
                worldId: string;
                cx: number;
                cy: number;
                r: number;
                /** @description thin = mine marker only (zoom 3); mid = includes ally/allySect (zoom 2) */
                lod?: "thin" | "mid";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sparse ownership overlay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldMapSparseView"];
                    };
                };
            };
        };
    };
    getWorldTile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single tile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldTileView"];
                    };
                };
            };
        };
    };
    getWorldMe: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player world state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    joinWorld: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    occupyTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Occupied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    abandonTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Abandoned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    relocateBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Relocated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    buildWatchtower: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Watchtower built */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldTileView"];
                    };
                };
            };
        };
    };
    getMarches: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active marches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"][];
                    };
                };
            };
        };
    };
    startMarch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    fromX: number;
                    fromY: number;
                    toX: number;
                    toY: number;
                    /** @enum {string} */
                    kind: "occupy" | "reinforce" | "attack" | "sweep" | "scout";
                    troops: number;
                    /** @description Siege attack team (G3-2c): attack formation template to use when kind=attack; committed troops = sum of troops allocated across all team units (overrides the troops field) */
                    teamId?: string;
                };
            };
        };
        responses: {
            /** @description March started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"];
                    };
                };
            };
        };
    };
    recallMarch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                marchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Recalled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    sweepTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    fromX: number;
                    fromY: number;
                    toX: number;
                    toY: number;
                    troops: number;
                };
            };
        };
        responses: {
            /** @description Sweep march started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"];
                    };
                };
            };
        };
    };
    distributeTroops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    /** @description Map of cardInstanceId to troop count to add */
                    allocations: {
                        [key: string]: number;
                    };
                };
            };
        };
        responses: {
            /** @description Troops distributed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    recoverCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    cardInstanceId: string;
                };
            };
        };
        responses: {
            /** @description Card recovered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    trainTroops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    qty: number;
                };
            };
        };
        responses: {
            /** @description Training queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    speedupTraining: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    coins: number;
                };
            };
        };
        responses: {
            /** @description Training sped up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    upgradeBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    key: components["schemas"]["BuildingKey"];
                };
            };
        };
        responses: {
            /** @description Build queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    speedupBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    coins: number;
                };
            };
        };
        responses: {
            /** @description Build sped up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    getDefense: {
        parameters: {
            query: {
                worldId: string;
                /** @description 'base' for the main base (default), or '{x}:{y}' for a territory tile key */
                tileKey?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current defense config (data null when unset) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["DefenseConfig"];
                    };
                };
            };
        };
    };
    setDefense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    /** @description 'base' for the main base, or '{x}:{y}' for a territory tile key; defaults to 'base' */
                    tileKey?: string;
                    defenseConfig: components["schemas"]["DefenseConfig"];
                };
            };
        };
        responses: {
            /** @description Defense set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getTeams: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attack formation templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["TeamTemplate"][];
                    };
                };
            };
        };
    };
    setTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    teams: components["schemas"]["TeamTemplate"][];
                };
            };
        };
        responses: {
            /** @description Teams saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getSiegeReplay: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path: {
                siegeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replayable siege battle (both combatants; spectator-only, non-authoritative) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SiegeReplayView"];
                    };
                };
            };
        };
    };
    getNations: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nation list (10 capitals) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["NationView"][];
                    };
                };
            };
        };
    };
    setNationName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capitalIdx: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Nation named */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getSeason: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Season info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SeasonView"];
                    };
                };
            };
        };
    };
    getSlgShopItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SLG shop items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SlgShopItemView"][];
                    };
                };
            };
        };
    };
    buySlgShopItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    itemId: string;
                };
            };
        };
        responses: {
            /** @description Item bought */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    listAuctions: {
        parameters: {
            query: {
                worldId: string;
                itemType?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"][];
                    };
                };
            };
        };
    };
    getMyAuctions: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"][];
                    };
                };
            };
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    /**
                     * @description card (CC-5): item.instanceId = CardInstance.id; gear must be empty; qty ignored (always 1)
                     * @enum {string}
                     */
                    itemType: "material" | "equipment" | "card";
                    item: {
                        [key: string]: unknown;
                    };
                    qty: number;
                    durationSec: number;
                    designatedBuyerId?: string;
                    /**
                     * @description Defaults to fixed (buy-now)
                     * @enum {string}
                     */
                    saleMode?: "fixed" | "auction";
                    /** @description Fixed-price buy-now unit price (required for fixed mode) */
                    price?: number;
                    /** @description Auction starting unit price (required for auction mode) */
                    startPrice?: number;
                    /** @description Auction buyout floor unit price (optional) */
                    buyoutPrice?: number;
                };
            };
        };
        responses: {
            /** @description Auction created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"];
                    };
                };
            };
        };
    };
    buyAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Bought */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    placeBid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    /** @description Bid unit price (coins per item) */
                    amount: number;
                };
            };
        };
        responses: {
            /** @description Bid placed (returns the closed AuctionView when the bid meets or exceeds buyoutPrice) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"];
                    };
                };
            };
        };
    };
    cancelAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    listSects: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sect list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectView"][];
                    };
                };
            };
        };
    };
    getSect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sect detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectDetailView"];
                    };
                };
            };
        };
    };
    createSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    name: string;
                    tag: string;
                };
            };
        };
        responses: {
            /** @description Sect created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectDetailView"];
                    };
                };
            };
        };
    };
    joinSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    sectId: string;
                };
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    leaveSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Left */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    dissolveSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Dissolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    allySect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetSectId: string;
                };
            };
        };
        responses: {
            /** @description Allied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    unallySect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetSectId: string;
                };
            };
        };
        responses: {
            /** @description Unallied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    voteRemoveSectLeader: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    nomineeFamilyId: string;
                };
            };
        };
        responses: {
            /** @description Vote tallied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectVoteResult"];
                    };
                };
            };
        };
    };
    sendSectMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    body: string;
                    senderName?: string;
                };
            };
        };
        responses: {
            /** @description Message sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectMessageView"];
                    };
                };
            };
        };
    };
    getSectChannel: {
        parameters: {
            query: {
                worldId: string;
                before?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectMessageView"][];
                    };
                };
            };
        };
    };
}
