/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/world/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/tile/{tileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinWorld"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/occupy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["occupyTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abandonTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/march": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarches"];
        put?: never;
        post: operations["startMarch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/march/{marchId}/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recallMarch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFamilies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFamily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["kickFamilyMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setFamilyRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/dissolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dissolveFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendFamilyMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFamilyChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/{auctionId}/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buyAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/{auctionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorldTileView: {
            x: number;
            y: number;
            /** @enum {string} */
            type: "neutral" | "resource" | "mountain" | "forest" | "water" | "center" | "familyKeep" | "base";
            level: number;
            /** @enum {string} */
            resType?: "food" | "iron" | "wood";
            occupied?: boolean;
            mine?: boolean;
            /** @description 占领者 9 位公开 id（meta 服务可用时填充） */
            ownerPublicId?: string;
            /** @description 占领者昵称（meta 服务可用时填充） */
            ownerName?: string;
            familyId?: string;
            garrison?: number;
            protectedUntil?: number;
        };
        WorldMapView: {
            worldId: string;
            cx: number;
            cy: number;
            r: number;
            tiles: components["schemas"]["WorldTileView"][];
        };
        PlayerWorldView: {
            joined: boolean;
            troops?: number;
            troopCap?: number;
            resources?: {
                [key: string]: number;
            };
            yieldRate?: {
                [key: string]: number;
            };
            mainBaseTile?: string;
            familyId?: string;
            territoryCount?: number;
        };
        MarchView: {
            marchId: string;
            /** @enum {string} */
            kind: "attack" | "reinforce" | "occupy" | "sweep" | "return";
            fromTile: string;
            toTile: string;
            troops: number;
            departAt: number;
            arriveAt: number;
            /** @enum {string} */
            status: "marching" | "returning" | "arrived";
        };
        FamilyMemberView: {
            accountId: string;
            publicId?: string;
            displayName?: string;
            /** @enum {string} */
            role: "leader" | "elder" | "member";
            joinedAt: number;
        };
        FamilyView: {
            familyId: string;
            name: string;
            tag: string;
            worldId: string;
            memberCount: number;
            leaderId: string;
            createdAt: number;
            members?: components["schemas"]["FamilyMemberView"][];
        };
        FamilyMessageView: {
            id: string;
            from: string;
            fromName?: string;
            body: string;
            ts: number;
        };
        AuctionView: {
            auctionId: string;
            worldId: string;
            sellerId: string;
            sellerName?: string;
            itemType: string;
            item: {
                [key: string]: unknown;
            };
            qty: number;
            price: number;
            /** @enum {string} */
            status: "open" | "sold" | "cancelled" | "expired";
            expireAt: number;
            designatedBuyerId?: string;
            taxPaid?: number;
            buyerId?: string;
        };
        OkResponse: {
            /** @enum {boolean} */
            ok: true;
        };
        MarchIdResponse: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWorldMap: {
        parameters: {
            query: {
                worldId: string;
                cx: number;
                cy: number;
                r: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map viewport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldMapView"];
                    };
                };
            };
        };
    };
    getWorldTile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single tile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldTileView"];
                    };
                };
            };
        };
    };
    getWorldMe: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player world state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    joinWorld: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    occupyTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Occupied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    abandonTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Abandoned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getMarches: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active marches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"][];
                    };
                };
            };
        };
    };
    startMarch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    fromX: number;
                    fromY: number;
                    toX: number;
                    toY: number;
                    /** @enum {string} */
                    kind: "occupy" | "reinforce" | "attack" | "sweep";
                    troops: number;
                };
            };
        };
        responses: {
            /** @description March started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"];
                    };
                };
            };
        };
    };
    recallMarch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                marchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Recalled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    listFamilies: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"][];
                    };
                };
            };
        };
    };
    getFamily: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"];
                    };
                };
            };
        };
    };
    createFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    name: string;
                    tag: string;
                };
            };
        };
        responses: {
            /** @description Family created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"];
                    };
                };
            };
        };
    };
    joinFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    familyId: string;
                };
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    leaveFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Left */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    kickFamilyMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetId: string;
                };
            };
        };
        responses: {
            /** @description Kicked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    setFamilyRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetId: string;
                    /** @enum {string} */
                    role: "leader" | "elder" | "member";
                };
            };
        };
        responses: {
            /** @description Role set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    dissolveFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Dissolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    sendFamilyMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    body: string;
                    senderName?: string;
                };
            };
        };
        responses: {
            /** @description Message sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            id: string;
                        };
                    };
                };
            };
        };
    };
    getFamilyChannel: {
        parameters: {
            query: {
                worldId: string;
                familyId: string;
                before?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyMessageView"][];
                    };
                };
            };
        };
    };
    listAuctions: {
        parameters: {
            query: {
                worldId: string;
                itemType?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"][];
                    };
                };
            };
        };
    };
    getMyAuctions: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"][];
                    };
                };
            };
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    itemType: string;
                    item: {
                        [key: string]: unknown;
                    };
                    qty: number;
                    price: number;
                    durationSec: number;
                    designatedBuyerId?: string;
                };
            };
        };
        responses: {
            /** @description Auction created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"];
                    };
                };
            };
        };
    };
    buyAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Bought */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    cancelAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
}
