/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/social/family/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyFamily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchFamilyByTag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["browseFamilies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFamilyJoinRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/requests/{requestId}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respondFamilyJoinRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFamily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/{familyId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestJoinFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["kickFamilyMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setFamilyMemberRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/disband": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disbandFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/announcement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setFamilyAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/family/{familyId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFamilyChannel"];
        put?: never;
        post: operations["sendFamilyMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/profile/{publicId}/extra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfileExtra"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFriends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFriendRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSocialBadges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchFriend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestFriend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respondFriend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeFriend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["blockFriend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/block/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["unblockFriend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/friends/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportFriend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/chat/{convId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/chat/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/chat/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markConversationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/mail/{mailId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["readMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/mail/{mailId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMail"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/social/mail/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        OkResponse: {
            /** @enum {boolean} */
            ok: true;
        };
        /** @enum {string} */
        FamilyRole: "leader" | "elder" | "member";
        FamilyView: {
            familyId: string;
            name: string;
            tag: string;
            leaderId: string;
            memberCount: number;
            prosperity: number;
            /** @description Prosperity decay anchor ms (worldsvc lazily decays sect-aggregate prosperity on read) */
            prosperityUpdatedAt?: number;
            /** @description Territory tile count (worldsvc-owned mirror) */
            territoryCount?: number;
            /** @description Sect the family currently belongs to (worldsvc-owned mirror; absent = independent family) */
            sectId?: string;
            /** @description Display name of the sect above, mirrored alongside sectId */
            sectName?: string;
            announcement?: string;
        };
        FamilyMemberView: {
            /** @description Omitted when the requester is not a member of this family (GET /social/family/:id is a public route reachable for any family id; internal accountIds are only exposed within the family itself). */
            accountId?: string;
            role: components["schemas"]["FamilyRole"];
            joinedAt: number;
            /** @description Resolved via metaserver batchProfiles; absent if the lookup is unavailable or the profile is gone */
            publicId?: string;
            displayName?: string;
            /** @description Equipped avatar id, composite "<category>:<key>" */
            avatarId?: string;
        };
        FamilyDetailView: components["schemas"]["FamilyView"] & {
            members: components["schemas"]["FamilyMemberView"][];
        };
        FamilyJoinRequestView: {
            requestId: string;
            accountId: string;
            publicId?: string;
            displayName?: string;
            createdAt: number;
        };
        FamilyMessageView: {
            id: string;
            senderId: string;
            senderName: string;
            /** @description Sender's equipped title (称号), if any */
            title?: string;
            /** @description Sender's family name — the family itself, since this channel is family-scoped */
            familyName?: string;
            body: string;
            ts: number;
        };
        ProfileExtraView: {
            rank?: string;
            elo?: number;
            familyName?: string;
            sectName?: string;
        };
        ProfileView: {
            publicId: string;
            displayName: string;
            rank?: string;
            equippedTitle?: string;
            avatarId?: string;
        };
        FriendView: {
            publicId: string;
            displayName: string;
            online: boolean;
            rank?: string;
            /** @description Owner-private alias for the friend */
            alias?: string;
            avatarId?: string;
        };
        FriendRequestView: {
            requestId: string;
            fromPublicId: string;
            fromName: string;
            toPublicId: string;
            message?: string;
            createdAt: number;
        };
        SocialBadges: {
            friendRequests: number;
            chat: number;
            mail: number;
            total: number;
        };
        ConversationView: {
            convId: string;
            peer: components["schemas"]["ProfileView"];
            lastBody?: string;
            lastFrom?: string;
            lastTs: number;
            unread: number;
        };
        ChatMessageView: {
            messageId: string;
            convId: string;
            fromPublicId: string;
            body: string;
            /** @enum {string} */
            kind: "text" | "system";
            ts: number;
        };
        MailAttachmentView: {
            /** @enum {string} */
            kind: "coins" | "item" | "skin" | "material" | "equipment" | "card";
            id?: string;
            count?: number;
            /** @description Present only for kind=equipment|card — the traded instance snapshot */
            instance?: {
                [key: string]: unknown;
            };
        };
        MailView: {
            mailId: string;
            /** @description 'system' or sender publicId */
            from: string;
            fromName?: string;
            subject: string;
            body: string;
            attachments?: components["schemas"]["MailAttachmentView"][];
            createdAt: number;
            expireAt: number;
            read: boolean;
            claimed: boolean;
        };
    };
    responses: {
        /** @description Error envelope */
        ErrorResp: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @enum {boolean} */
                    ok: false;
                    error: components["schemas"]["Error"];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's own family (including member list), or null if not a member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyDetailView"] | null;
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    searchFamilyByTag: {
        parameters: {
            query: {
                tag: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family matching the TAG (exact match, case-insensitive), or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"] | null;
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    browseFamilies: {
        parameters: {
            query?: {
                /** @description Fuzzy name match */
                q?: string;
                /** @description Default 10, clamped to [1, 50] */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Joinable families (open slot), sorted by prosperity desc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"][];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    createFamily: {
        parameters: {
            query?: never;
            header?: {
                /** @description Content-filter region for the family name (CONTENT_MODERATION_DESIGN.md); defaults to global */
                "X-Chat-Region"?: "global" | "cn" | "de" | "en";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description 2-5 uppercase alphanumeric chars, globally unique */
                    tag: string;
                };
            };
        };
        responses: {
            /** @description Family created; caller becomes leader */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyDetailView"];
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            409: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    listFamilyJoinRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending join requests for the caller's own family (leader/elder only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            requests: components["schemas"]["FamilyJoinRequestView"][];
                        };
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    respondFamilyJoinRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Rejecting mails the applicant (family.mail.rejected.* i18n key) */
                    accept: boolean;
                };
            };
        };
        responses: {
            /** @description Accepted or rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getFamily: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family details (including member list), or null if not found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyDetailView"] | null;
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    requestJoinFamily: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Join request submitted (pending leader/elder approval); does not add membership yet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            requestId: string;
                        };
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            409: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    leaveFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Left the family (leader must transfer leadership or dissolve first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    kickFamilyMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description accountId of the member to kick */
                    targetId: string;
                };
            };
        };
        responses: {
            /** @description Member kicked (leader can kick anyone; elder can only kick members) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    setFamilyMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description accountId of the member */
                    targetId: string;
                    role: components["schemas"]["FamilyRole"];
                };
            };
        };
        responses: {
            /** @description Role updated (leader only; cannot promote to leader via this endpoint) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    disbandFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family dissolved (leader only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    setFamilyAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Max 200 chars (leader/elder only) */
                    announcement: string;
                };
            };
        };
        responses: {
            /** @description Announcement updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getFamilyChannel: {
        parameters: {
            query?: {
                /** @description ms-epoch cursor (reverse-chronological pagination) */
                before?: number;
                /** @description Default 30, clamped to [1, 50] */
                limit?: number;
            };
            header?: never;
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family channel history (caller must be a member) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyMessageView"][];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    sendFamilyMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Chat-filter region (CONTENT_MODERATION_DESIGN.md); defaults to global */
                "X-Chat-Region"?: "global" | "cn" | "de" | "en";
            };
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                    /** @description Client-supplied fallback; server prefers the resolved meta displayName */
                    senderName?: string;
                };
            };
        };
        responses: {
            /** @description Message sent (pushed in real time to all other online members) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyMessageView"];
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getProfileExtra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unified profile-popup extras (rank/ELO + family/sect, if any); empty object if unresolvable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["ProfileExtraView"];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getFriends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Friend list (includes online status) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            friends: components["schemas"]["FriendView"][];
                        };
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getFriendRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending friend requests (received + sent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            incoming: components["schemas"]["FriendRequestView"][];
                            outgoing: components["schemas"]["FriendRequestView"][];
                        };
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getSocialBadges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offline badge aggregate (friend requests / unread conversations / unread mail + total) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SocialBadges"];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    searchFriend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicId: string;
                };
            };
        };
        responses: {
            /** @description Player found by public id (404 if not found) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            profile: components["schemas"]["ProfileView"];
                        };
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    requestFriend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicId: string;
                    message?: string;
                };
            };
        };
        responses: {
            /** @description Friend request sent (or the existing pending request, if one was already outstanding) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            requestId: string;
                        };
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            409: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    respondFriend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    requestId: string;
                    accept: boolean;
                };
            };
        };
        responses: {
            /** @description Accepted (creates a bidirectional friend edge) or declined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            409: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    removeFriend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Friend removed (bidirectional) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    blockFriend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicId: string;
                };
            };
        };
        responses: {
            /** @description Player blocked (removes friendship, blocks requests/messages) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    unblockFriend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player unblocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    reportFriend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicId: string;
                    /** @description Free-text reason, truncated server-side to REPORT_REASON_MAX */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Report filed for ops/admin review (COMPLIANCE_GLOBAL.md §7); 404 if publicId is unresolvable or refers to the caller themself */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation list (per-conversation unread count + last message snippet) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            conversations: components["schemas"]["ConversationView"][];
                        };
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getChatMessages: {
        parameters: {
            query?: {
                /** @description ms-epoch cursor */
                before?: number;
                /** @description Default 30, clamped to [1, 50] */
                limit?: number;
            };
            header?: never;
            path: {
                convId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation history (paginated, reverse chronological); 404 if not a member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            messages: components["schemas"]["ChatMessageView"][];
                        };
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Chat-filter region; defaults to global */
                "X-Chat-Region"?: "global" | "cn" | "de" | "en";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    toPublicId: string;
                    body: string;
                };
            };
        };
        responses: {
            /** @description Message sent (must be mutual friends; rate-limited per account) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            messageId: string;
                            ts: number;
                        };
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            429: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    markConversationRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    convId: string;
                };
            };
        };
        responses: {
            /** @description Conversation marked read (clears unread count) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    getMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inbox (mail list + unread count) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            mail: components["schemas"]["MailView"][];
                            unread: number;
                        };
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    readMail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mail marked read (404 if not found) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    deleteMail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mailId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mail deleted (MAIL_HAS_UNCLAIMED_ATTACHMENT error if an attachment has not been claimed yet) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["OkResponse"];
                    };
                };
            };
            401: components["responses"]["ErrorResp"];
            409: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
    sendMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    toPublicId: string;
                    subject: string;
                    body?: string;
                };
            };
        };
        responses: {
            /** @description Mail sent between players (must be mutual friends; no attachments) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            mailId: string;
                        };
                    };
                };
            };
            400: components["responses"]["ErrorResp"];
            401: components["responses"]["ErrorResp"];
            403: components["responses"]["ErrorResp"];
            404: components["responses"]["ErrorResp"];
            500: components["responses"]["ErrorResp"];
        };
    };
}
