/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/world/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/tile/{tileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinWorld"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/occupy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["occupyTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abandonTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/relocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 主动迁城（花 RELOCATE_COST 金币把主城迁到 (x,y)，保留全部领地） */
        post: operations["relocateBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/march": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarches"];
        put?: never;
        post: operations["startMarch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/march/{marchId}/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recallMarch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sweepTile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/troops/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trainTroops"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/troops/speedup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["speedupTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/defense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefense"];
        put: operations["setDefense"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeams"];
        put: operations["setTeams"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/siege/{siegeId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSiegeReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/nations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/nations/{capitalIdx}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setNationName"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/shop/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSlgShopItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/shop/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buySlgShopItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFamilies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFamily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["kickFamilyMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setFamilyRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/dissolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dissolveFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendFamilyMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/family/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFamilyChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/{auctionId}/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buyAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auction/{auctionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/{sectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/dissolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dissolveSect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/ally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["allySect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/unally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unallySect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/vote-remove-leader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["voteRemoveSectLeader"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendSectMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sect/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSectChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorldTileView: {
            x: number;
            y: number;
            /** @enum {string} */
            type: "neutral" | "resource" | "territory" | "familyKeep" | "center" | "base" | "obstacle" | "gate" | "stronghold";
            level: number;
            /** @enum {string} */
            resType?: "food" | "iron" | "wood";
            occupied?: boolean;
            mine?: boolean;
            /** @description 占领者 9 位公开 id（meta 服务可用时填充） */
            ownerPublicId?: string;
            /** @description 占领者昵称（meta 服务可用时填充） */
            ownerName?: string;
            familyId?: string;
            garrison?: number;
            protectedUntil?: number;
            /** @description G5 视野：该格是否在请求者当前视野内。true=动态层如实返回；false=视野外，仅程序化 底层地形（动态层全部隐去，含「已被占领」信号）。仅 /world/map 视区读填充。 */
            visible?: boolean;
            /** @description G5：该格归同家族盟友所有（视野内、非己方）。客户端用友方色渲染。 */
            ally?: boolean;
            /** @description G5：该格归本宗门「联盟宗门」成员所有（视野内、非己方、非家族）。联盟不共享视野， 仅在地图上用黄描边标记区分（§8.2，盟友间禁止进攻/夺地）。 */
            allySect?: boolean;
        };
        WorldMapView: {
            worldId: string;
            cx: number;
            cy: number;
            r: number;
            tiles: components["schemas"]["WorldTileView"][];
        };
        PlayerWorldView: {
            joined: boolean;
            troops?: number;
            troopCap?: number;
            resources?: {
                [key: string]: number;
            };
            yieldRate?: {
                [key: string]: number;
            };
            mainBaseTile?: string;
            familyId?: string;
            territoryCount?: number;
            /** @description 训练队列（S8-2，按 completeAt 升序）。客户端据此渲染队列倒计时（C4）。 */
            trainingQueue?: {
                qty: number;
                /** Format: int64 */
                startAt: number;
                /** Format: int64 */
                completeAt: number;
            }[];
        };
        MarchView: {
            marchId: string;
            /** @enum {string} */
            kind: "attack" | "reinforce" | "occupy" | "sweep" | "scout" | "return";
            fromTile: string;
            toTile: string;
            troops: number;
            departAt: number;
            arriveAt: number;
            /** @enum {string} */
            status: "marching" | "returning" | "arrived";
            /** @description G5：是否为请求者自己的行军（false = 视野内的敌方行军） */
            mine?: boolean;
        };
        FamilyMemberView: {
            accountId: string;
            publicId?: string;
            displayName?: string;
            /** @enum {string} */
            role: "leader" | "elder" | "member";
            joinedAt: number;
        };
        FamilyView: {
            familyId: string;
            name: string;
            tag: string;
            worldId: string;
            memberCount: number;
            leaderId: string;
            createdAt: number;
            sectId?: string;
            members?: components["schemas"]["FamilyMemberView"][];
        };
        FamilyMessageView: {
            id: string;
            from: string;
            fromName?: string;
            body: string;
            ts: number;
        };
        AuctionView: {
            auctionId: string;
            worldId: string;
            sellerId: string;
            sellerName?: string;
            itemType: string;
            item: {
                [key: string]: unknown;
            };
            qty: number;
            price: number;
            /** @enum {string} */
            status: "open" | "sold" | "cancelled" | "expired";
            expireAt: number;
            designatedBuyerId?: string;
            taxPaid?: number;
            buyerId?: string;
        };
        SectView: {
            sectId: string;
            worldId: string;
            name: string;
            tag: string;
            leaderFamilyId: string;
            leaderId: string;
            memberFamilyCount: number;
            allySectIds: string[];
            prosperity: number;
        };
        SectMemberFamilyView: {
            familyId: string;
            name: string;
            tag: string;
            leaderId: string;
            memberCount: number;
            territoryCount: number;
        };
        SectDetailView: components["schemas"]["SectView"] & {
            memberFamilies: components["schemas"]["SectMemberFamilyView"][];
            removalVote?: {
                nomineeFamilyId: string;
                voteCount: number;
                needed: number;
            };
        };
        SectMessageView: {
            id: string;
            senderId: string;
            senderName: string;
            body: string;
            ts: number;
        };
        SectVoteResult: {
            passed: boolean;
            voteCount: number;
            needed: number;
        };
        NationView: {
            /** @description 0~9，对应 CAPITAL_FRACTIONS 索引 */
            capitalIdx: number;
            x: number;
            y: number;
            ownerId?: string;
            familyId?: string;
            nationName?: string;
            foundedAt?: number;
        };
        SeasonView: {
            worldId: string;
            season: number;
            shard: number;
            /** @enum {string} */
            status: "open" | "active" | "settling" | "closed";
            openAt: number;
            resetAt?: number;
            capacity: number;
            population: number;
            mapW: number;
            mapH: number;
        };
        SlgShopItemView: {
            id: string;
            /** @description 金币价格 */
            cost: number;
            /** @enum {string} */
            kind: "troop_speedup" | "resource_pack" | "protection" | "battle_pass";
            effect: {
                [key: string]: unknown;
            };
            description: string;
        };
        SiegeReplayView: {
            siegeId: string;
            seed: number;
            /** @enum {string} */
            outcome: "attacker_win" | "defender_win" | "draw";
            level: {
                [key: string]: unknown;
            };
        };
        ArmyEntry: {
            unitType: string;
            col: number;
            row: number;
            initialHp?: number;
        };
        TeamTemplate: {
            id: string;
            name: string;
            army: components["schemas"]["ArmyEntry"][];
        };
        DefenseConfig: {
            [key: string]: unknown;
        };
        OkResponse: {
            /** @enum {boolean} */
            ok: true;
        };
        MarchIdResponse: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWorldMap: {
        parameters: {
            query: {
                worldId: string;
                cx: number;
                cy: number;
                r: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map viewport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldMapView"];
                    };
                };
            };
        };
    };
    getWorldTile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single tile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["WorldTileView"];
                    };
                };
            };
        };
    };
    getWorldMe: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player world state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    joinWorld: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    occupyTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Occupied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    abandonTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Abandoned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    relocateBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    x: number;
                    y: number;
                };
            };
        };
        responses: {
            /** @description Relocated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    getMarches: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active marches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"][];
                    };
                };
            };
        };
    };
    startMarch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    fromX: number;
                    fromY: number;
                    toX: number;
                    toY: number;
                    /** @enum {string} */
                    kind: "occupy" | "reinforce" | "attack" | "sweep" | "scout";
                    troops: number;
                    /** @description 围攻挂队（G3-2c）：attack 时用此进攻布阵模板；committed 兵力 = 队伍各单位分配之和（覆盖 troops） */
                    teamId?: string;
                };
            };
        };
        responses: {
            /** @description March started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"];
                    };
                };
            };
        };
    };
    recallMarch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                marchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Recalled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    sweepTile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    fromX: number;
                    fromY: number;
                    toX: number;
                    toY: number;
                    troops: number;
                };
            };
        };
        responses: {
            /** @description Sweep march started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["MarchView"];
                    };
                };
            };
        };
    };
    trainTroops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    qty: number;
                };
            };
        };
        responses: {
            /** @description Training queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    speedupTraining: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    coins: number;
                };
            };
        };
        responses: {
            /** @description Training sped up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["PlayerWorldView"];
                    };
                };
            };
        };
    };
    getDefense: {
        parameters: {
            query: {
                worldId: string;
                /** @description 'base' 主城（缺省），或 '{x}:{y}' 领地键 */
                tileKey?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current defense config (data null when unset) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["DefenseConfig"];
                    };
                };
            };
        };
    };
    setDefense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    /** @description 'base' 主城，或 '{x}:{y}' 领地键；缺省 'base' */
                    tileKey?: string;
                    defenseConfig: components["schemas"]["DefenseConfig"];
                };
            };
        };
        responses: {
            /** @description Defense set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getTeams: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attack formation templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["TeamTemplate"][];
                    };
                };
            };
        };
    };
    setTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    teams: components["schemas"]["TeamTemplate"][];
                };
            };
        };
        responses: {
            /** @description Teams saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getSiegeReplay: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path: {
                siegeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replayable siege battle (both combatants; spectator-only, non-authoritative) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SiegeReplayView"];
                    };
                };
            };
        };
    };
    getNations: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nation list (10 capitals) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["NationView"][];
                    };
                };
            };
        };
    };
    setNationName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capitalIdx: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Nation named */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getSeason: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Season info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SeasonView"];
                    };
                };
            };
        };
    };
    getSlgShopItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SLG shop items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SlgShopItemView"][];
                    };
                };
            };
        };
    };
    buySlgShopItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    itemId: string;
                };
            };
        };
        responses: {
            /** @description Item bought */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    listFamilies: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"][];
                    };
                };
            };
        };
    };
    getFamily: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                familyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"];
                    };
                };
            };
        };
    };
    createFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    name: string;
                    tag: string;
                };
            };
        };
        responses: {
            /** @description Family created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyView"];
                    };
                };
            };
        };
    };
    joinFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    familyId: string;
                };
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    leaveFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Left */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    kickFamilyMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetId: string;
                };
            };
        };
        responses: {
            /** @description Kicked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    setFamilyRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetId: string;
                    /** @enum {string} */
                    role: "leader" | "elder" | "member";
                };
            };
        };
        responses: {
            /** @description Role set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    dissolveFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Dissolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    sendFamilyMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    body: string;
                    senderName?: string;
                };
            };
        };
        responses: {
            /** @description Message sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: {
                            id: string;
                        };
                    };
                };
            };
        };
    };
    getFamilyChannel: {
        parameters: {
            query: {
                worldId: string;
                familyId: string;
                before?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["FamilyMessageView"][];
                    };
                };
            };
        };
    };
    listAuctions: {
        parameters: {
            query: {
                worldId: string;
                itemType?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"][];
                    };
                };
            };
        };
    };
    getMyAuctions: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"][];
                    };
                };
            };
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    itemType: string;
                    item: {
                        [key: string]: unknown;
                    };
                    qty: number;
                    price: number;
                    durationSec: number;
                    designatedBuyerId?: string;
                };
            };
        };
        responses: {
            /** @description Auction created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["AuctionView"];
                    };
                };
            };
        };
    };
    buyAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Bought */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    cancelAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    listSects: {
        parameters: {
            query: {
                worldId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sect list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectView"][];
                    };
                };
            };
        };
    };
    getSect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sect detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectDetailView"];
                    };
                };
            };
        };
    };
    createSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    name: string;
                    tag: string;
                };
            };
        };
        responses: {
            /** @description Sect created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectDetailView"];
                    };
                };
            };
        };
    };
    joinSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    sectId: string;
                };
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    leaveSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Left */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    dissolveSect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                };
            };
        };
        responses: {
            /** @description Dissolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    allySect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetSectId: string;
                };
            };
        };
        responses: {
            /** @description Allied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    unallySect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    targetSectId: string;
                };
            };
        };
        responses: {
            /** @description Unallied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    voteRemoveSectLeader: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    nomineeFamilyId: string;
                };
            };
        };
        responses: {
            /** @description Vote tallied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectVoteResult"];
                    };
                };
            };
        };
    };
    sendSectMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    worldId: string;
                    body: string;
                    senderName?: string;
                };
            };
        };
        responses: {
            /** @description Message sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectMessageView"];
                    };
                };
            };
        };
    };
    getSectChannel: {
        parameters: {
            query: {
                worldId: string;
                before?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] & {
                        data?: components["schemas"]["SectMessageView"][];
                    };
                };
            };
        };
    };
}
