// Commercial database factory (S5-1, COMMERCIAL_DESIGN §3/§7). Database name notebook_wars_commercial,
// physically isolated from the meta database. Collections: wallets / ledger / orders / recharges / gachaHistory.
import { MongoClient, Db, Collection, type MongoClientOptions } from 'mongodb';
import type { Rarity, LimitedPoolConfig, CustomPoolCategory } from '@nw/shared';
import type { RechargeChannel } from './spendChannel';

/** Balance (single-document atomic update + optimistic lock rev). pity embedded in the same document (design default A: coin deduction + pity counter in one atomic operation). */
export interface WalletDoc {
  _id: string; // accountId
  coins: number; // >= 0
  rev: number;
  gacha: { pity: Record<string, number> }; // poolId → cumulative draws since last legendary
  /** Timestamp of first-ever successful IAP (ms). Absent = never purchased; gates the first-purchase 2× bonus. */
  firstPurchasedAt?: number;
  /** Fate points (GACHA_DESIGN §7): earned on off-banner limited legendaries, redeemed 30 → 1 self-chosen legendary. */
  fatePoints?: number;
  /** Monthly card subscription (GACHA_DESIGN §5). expiry = subscription end (ms); lastClaimDayKey = last daily-coin claim UTC day. */
  subscription?: { expiry: number; lastClaimDayKey?: string };
  /** One-off products already purchased (GACHA_DESIGN §6): product ids in economy.PRODUCT_STARTER_* (once-per-account guard). */
  starterUsed?: string[];
  /**
   * Lifetime cumulative real-money spend in usdCents (GACHA_DESIGN §13, ADR-045). Monotonic except for
   * Paddle refunds (paddleRefund decrements, floored at 0). $inc'd in the same atomic op as credit()'s
   * coins update — see credit()'s rechargeUsdCents ref. Absent = 0 (never purchased / pre-feature wallet).
   */
  totalRechargeCents?: number;
  /**
   * Real-money top-up balance, tagged by payment-channel bucket (ADR-020, spendChannel.ts). Spendable only
   * when the request's client platform maps to that same bucket — prevents e.g. Paddle-bought coins being
   * spent inside the iOS app, which would violate Apple's anti-circumvention IAP terms. `coins` remains the
   * always-spendable free pool (earned via ads/victory/promo/refund/grant, or grandfathered pre-migration
   * recharges — this wallet shipped before channel tagging existed, so historical balances are not
   * retroactively split by channel). Absent/0 per key = no top-up on that channel yet.
   */
  recharged?: Partial<Record<RechargeChannel, number>>;
  updatedAt: number;
}

/** Immutable ledger entry (one record per credit/debit, for auditing/reconciliation). */
export interface LedgerDoc {
  accountId: string;
  delta: number;
  balanceAfter: number;
  reason: string; // shop | gacha | gacha_refund | recharge | ads
  orderId?: string;
  receiptId?: string;
  ts: number;
}

export interface GachaResultEntry {
  itemId: string;
  rarity: Rarity;
}

/** Purchase order (idempotency key orderId + pending delivery reconciliation saga). */
export interface OrderDoc {
  _id: string; // orderId (UUID generated by meta)
  accountId: string;
  // 'sink' = pure coin consumption (e.g. rename), no item delivery, lands in DB as status:'delivered', not picked up by reconciliation.
  // 'grant' = pure coin grant (mail attachment claim S6-3), same as sink: delivered on insert, not picked up by reconciliation.
  // 'fate' = Fate Point redemption (GACHA_DESIGN §7): points already deducted, meta delivers the chosen legendary skin (like gacha).
  // 'starter' = starter pack (GACHA_DESIGN §6): coins/subscription already applied, meta delivers pack items (like gacha).
  kind: 'shop' | 'gacha' | 'sink' | 'grant' | 'fate' | 'starter';
  cost: number;
  status: 'charged' | 'delivered';
  coinsAfter: number; // balance after coin deduction (for idempotent replay)
  // qty: units charged/delivered together in one shopCharge call (bulk-buy, ×10 button, 2026-08-10);
  // absent/1 for every pre-existing order and every other kind. Kept on the order so a crash between
  // charge and delivery (reconcileUndelivered) replays the exact quantity that was actually paid for.
  result: { itemId?: string; results?: GachaResultEntry[]; poolId?: string; qty?: number };
  pityAfter?: Record<string, number>;
  refundCoins?: number; // duplicate refund coins computed by meta in the delivery callback (credited on delivered)
  deliveredAt?: number;
  ts: number;
  /**
   * CAS guard (base.ts's claimOrderResume / orders.ts's healOrderRefund): set the instant a caller claims
   * the exclusive right to run this order's pending side effect (resume a stale 'charged' grant, or credit
   * a missed delivery refund). Without it, two concurrent stale-claim healers both pass their isStaleClaim
   * + ledger-absence reads (neither has credited yet) and both proceed to credit/applySubscription —
   * a double-grant. Only the caller whose findOneAndUpdate matches (field still absent) proceeds.
   */
  healClaimedAt?: number;
}

/** Top-up receipt (idempotency key receiptId + duplicate coin prevention). */
export interface RechargeDoc {
  _id: string; // receiptId
  accountId: string;
  platform: string;
  coinsGranted: number;
  status: 'granted';
  rawReceipt: string;
  ts: number;
  /**
   * usdCents credited to totalRechargeCents for this recharge (GACHA_DESIGN §13). Stored so a later Paddle
   * refund can decrement the wallet by the exact amount originally added, without re-deriving it from
   * coinsGranted (which may include the first-purchase 2× bonus and would double-refund the counter).
   */
  usdCents?: number;
  /** Set once this receipt has been refunded (paddleRefund), so a re-delivered refund event is a no-op. */
  refundedAt?: number;
  /**
   * CAS guard (recharge.ts's healRechargeCredit): set the instant a caller claims the exclusive right to
   * heal this stale receipt's missed credit. Without it, two concurrent stale-claim healers both pass the
   * isStaleClaim + ledger-absence reads and both call credit() — a double-grant.
   */
  healedAt?: number;
  /**
   * Present only for non-coin receipts (subscription cards / starter packs, verifyNonCoinReceipt) —
   * absent for ordinary coin recharges. Lets a replayed receiptId be checked against the caller's
   * expected product, so a monthly-card receipt can't later be replayed as a year-card/starter claim.
   */
  product?: 'monthly_card' | 'year_card' | 'starter_draw' | 'starter_growth';
}

/**
 * Paddle webhook event log (all `event_type`s, not just `transaction.completed` — that one also lands in
 * `recharges` via paddleComplete()). Support/CS lookup for "why didn't my payment go through": failed/canceled
 * transactions are otherwise dropped silently by the webhook handler. _id = `${transactionId}:${eventType}`
 * (naturally unique per event occurrence; Paddle may resend the same event, so this also dedupes retries).
 */
export interface PaddleEventDoc {
  _id: string; // `${transactionId}:${eventType}`
  transactionId: string;
  eventType: string;
  status?: string;
  accountId?: string;
  rawEvent: string; // JSON.stringify(event) — full payload for support diagnosis
  ts: number;
}

/**
 * Apple subscription → account link. `_id` is the `originalTransactionId`, the one id that stays
 * constant across every renewal of a subscription (and across reinstalls, device changes and
 * storefront changes).
 *
 * Why this table has to exist: an App Store Server Notification announcing a renewal carries Apple's
 * ids and nothing of ours — no account, no session, no header we control. The only moment both facts
 * are in hand is the original purchase, which arrives on an authenticated request; so that is where
 * the pairing is written down, and every later renewal is matched by looking it up here. Without it a
 * DID_RENEW notification is unroutable and the player silently stops being paid for.
 *
 * Written on every successful Apple subscription verification, not just the first — a Restore
 * Purchases or a re-verify re-asserts the same row, so a link can heal rather than being a one-shot
 * value that is lost forever if it misses.
 */
export interface AppleTransactionLinkDoc {
  _id: string; // originalTransactionId (naturally unique)
  accountId: string;
  product: 'monthly_card' | 'year_card';
  /** Apple's per-Apple-Account-per-app id (WWDC25). Only present on recent OS versions, so it is
   *  recorded when offered and never relied on as the routing key. */
  appTransactionId?: string;
  linkedAt: number;
  updatedAt: number;
}

/**
 * Every App Store Server Notification we accept, logged for support ("the player says they were
 * charged / refunded — what did Apple actually tell us"). Mirrors what `paddleEvents` does for the
 * web channel, which previously had no Apple counterpart at all.
 *
 * `_id` is Apple's `notificationUUID`, which also dedupes Apple's at-least-once redelivery.
 */
export interface AppleNotificationDoc {
  _id: string; // notificationUUID
  notificationType: string;
  subtype?: string;
  /** Resolved account, when the notification could be routed to one; absent means it could not be. */
  accountId?: string;
  transactionId?: string;
  originalTransactionId?: string;
  productId?: string;
  /** CONSUMPTION_REQUEST only: why the customer asked for a refund (notifications v2.11+). */
  consumptionRequestReason?: string;
  /** What we did about it — 'granted' | 'ignored' | 'unlinked' | 'consumption_sent' | 'consumption_failed'. */
  outcome: string;
  ts: number;
}

/**
 * appAccountToken -> account. Apple's own "which of your users does this purchase belong to" field:
 * the client attaches it to the StoreKit 2 purchase, and Apple then echoes it back on the
 * transaction and on every notification about it (appleServerApi.ts's AppleTransaction).
 *
 * Why this exists alongside AppleTransactionLinkDoc rather than replacing it: a link row can only be
 * written when a purchase is REPORTED, which leaves a hole nothing can close afterwards -- the charge
 * succeeds, the app is killed before it POSTs, and every later notification about that subscription
 * is unroutable forever. This row is written BEFORE the purchase, when the account asks for its
 * token, so that hole closes. The link table stays as the fallback: StoreKit 1 purchases carry no
 * token at all, and a token can be missing from an older transaction.
 *
 * `_id` is the token because token -> account is the direction the notification path looks up. One
 * row per account for the lifetime of the account: the token is allocated once and reused, so every
 * purchase a player ever makes carries the same one and a support query by account is a single hit.
 */
export interface AppleAccountTokenDoc {
  _id: string; // appAccountToken (UUID v4)
  accountId: string;
  createdAt: number;
}

/**
 * Whether a player agreed to let us answer Apple's CONSUMPTION_REQUEST with their consumption data
 * (service/appleConsumption.ts). Apple requires `customerConsented: true` AND requires the consent to
 * be collected by the app from the customer; a submission reporting false is rejected outright, so an
 * account with no row here gets no reply sent on its behalf at all.
 *
 * Stored per account rather than per purchase: the question the app asks ("may we share how much of a
 * purchase you used, if you ask Apple for a refund?") is not about one transaction, and asking again
 * per purchase would be a worse experience for no more information.
 */
export interface AppleConsumptionConsentDoc {
  _id: string; // accountId
  consented: boolean;
  ts: number;
}

/** Gacha draw history (persisted per draw, M7). */
export interface GachaHistoryDoc {
  accountId: string;
  poolId: string;
  orderId: string;
  results: GachaResultEntry[];
  pityBefore: number;
  pityAfter: number;
  ts: number;
}

/** Promo code definition (B-PROMO). _id = code string (normalized to uppercase). */
export interface PromoCodeDoc {
  _id: string; // code (already normalized to uppercase)
  coins: number; // coins granted on redemption
  expiresAt?: number; // expiry timestamp (ms), defaults to never
  totalLimit?: number; // global redemption cap (defaults to unlimited)
  redeemed: number; // number of times redeemed (atomic $inc)
  note?: string; // operator note
  createdBy: string; // adminId
  createdAt: number;
}

/** Promo code redemption record (B-PROMO). _id = `${accountId}:${code}` is naturally unique, preventing duplicate redemptions. */
export interface PromoRedemptionDoc {
  _id: string; // `${accountId}:${code}`
  accountId: string;
  code: string;
  coinsGranted: number;
  ts: number;
  /**
   * CAS guard (promo.ts's healOrRejectPromoReplay): set the instant a caller claims the exclusive right to
   * heal this stale redemption's missed credit. Without it, two concurrent stale-claim healers both pass
   * the isStaleClaim + ledger-absence reads and both call credit() — a double-grant.
   */
  healedAt?: number;
}

/**
 * Gacha pool config stored in `gachaPools`. Two kinds share the collection (discriminated by `kind`,
 * absent = 'derived' for backward compatibility with pre-§12 docs):
 *   · derived — GACHA_DESIGN §2.2 limited pool: content derived from the standard pool
 *     (economy.buildLimitedPool), featured legendary + Fate Points. Retained after close so
 *     past-featured legendaries stay redeemable with Fate Points (§7).
 *   · custom  — GACHA_DESIGN §12 ops-authored pool: free-form categories/items/weights, no pity/fate.
 */
export interface DerivedGachaPoolDoc extends LimitedPoolConfig {
  _id: string; // = LimitedPoolConfig.id
  kind?: 'derived';
  createdBy: string; // adminId
  createdAt: number;
  closedAt?: number; // set when an admin closes the pool early (endAt is also clamped to now)
}

export interface CustomGachaPoolDoc {
  _id: string; // = pool id
  kind: 'custom';
  id: string;
  name: string;
  costSingle: number;
  costTen?: number; // defaults to costSingle * 10
  startAt: number;
  endAt: number;
  categories: CustomPoolCategory[];
  createdBy: string; // adminId
  createdAt: number;
  closedAt?: number;
}

export type GachaPoolDoc = DerivedGachaPoolDoc | CustomGachaPoolDoc;

/** Narrow a stored pool doc to the ops-authored custom kind (GACHA_DESIGN §12). */
export function isCustomPoolDoc(doc: GachaPoolDoc): doc is CustomGachaPoolDoc {
  return doc.kind === 'custom';
}

export interface CommercialCollections {
  wallets: Collection<WalletDoc>;
  ledger: Collection<LedgerDoc>;
  orders: Collection<OrderDoc>;
  recharges: Collection<RechargeDoc>;
  paddleEvents: Collection<PaddleEventDoc>;
  appleTransactionLinks: Collection<AppleTransactionLinkDoc>;
  appleNotifications: Collection<AppleNotificationDoc>;
  appleAccountTokens: Collection<AppleAccountTokenDoc>;
  appleConsumptionConsents: Collection<AppleConsumptionConsentDoc>;
  gachaHistory: Collection<GachaHistoryDoc>;
  promoCodes: Collection<PromoCodeDoc>;
  promoRedemptions: Collection<PromoRedemptionDoc>;
  gachaPools: Collection<GachaPoolDoc>;
}

export interface CommercialMongo {
  client: MongoClient;
  db: Db;
  collections: CommercialCollections;
  ensureIndexes(): Promise<void>;
  close(): Promise<void>;
}

export async function createCommercialMongo(
  uri: string,
  dbName: string,
  options?: MongoClientOptions,
): Promise<CommercialMongo> {
  const client = new MongoClient(uri, options);
  try {
    await client.connect();
  } catch (err) {
    // On connection failure, log a clear, redacted error message before rethrowing to avoid a silent crash during startup.
    const safeUri = uri.replace(/\/\/[^@/]*@/, '//<redacted>@');
    console.error(
      `[commercial-mongo] Failed to connect to MongoDB (uri=${safeUri}, db=${dbName}): ` +
        `${(err as Error).message}. Please ensure the database is running and the connection config (NW_COMM_MONGO_URI) is correct.`,
    );
    throw err;
  }
  const db = client.db(dbName);
  const collections: CommercialCollections = {
    wallets: db.collection<WalletDoc>('wallets'),
    ledger: db.collection<LedgerDoc>('ledger'),
    orders: db.collection<OrderDoc>('orders'),
    recharges: db.collection<RechargeDoc>('recharges'),
    paddleEvents: db.collection<PaddleEventDoc>('paddleEvents'),
    appleTransactionLinks: db.collection<AppleTransactionLinkDoc>('appleTransactionLinks'),
    appleNotifications: db.collection<AppleNotificationDoc>('appleNotifications'),
    appleAccountTokens: db.collection<AppleAccountTokenDoc>('appleAccountTokens'),
    appleConsumptionConsents: db.collection<AppleConsumptionConsentDoc>('appleConsumptionConsents'),
    gachaHistory: db.collection<GachaHistoryDoc>('gachaHistory'),
    promoCodes: db.collection<PromoCodeDoc>('promoCodes'),
    promoRedemptions: db.collection<PromoRedemptionDoc>('promoRedemptions'),
    gachaPools: db.collection<GachaPoolDoc>('gachaPools'),
  };

  async function ensureIndexes(): Promise<void> {
    await collections.ledger.createIndex({ accountId: 1, ts: -1 });
    // Coin-anomaly daily audit (COMMERCIAL_DESIGN §6.6): scans/groups the whole ledger by ts range across ALL
    // accounts, not just one — {accountId,ts} above doesn't help that scan pattern.
    await collections.ledger.createIndex({ ts: 1 });
    await collections.orders.createIndex({ accountId: 1, status: 1 });
    // Reconciliation scan: undelivered orders (status:'charged') by time.
    await collections.orders.createIndex({ status: 1, ts: 1 });
    await collections.gachaHistory.createIndex({ accountId: 1, ts: -1 });
    // paddleEvents._id = transactionId:eventType is naturally unique; index for support lookup by account/transaction.
    await collections.paddleEvents.createIndex({ accountId: 1, ts: -1 });
    await collections.paddleEvents.createIndex({ transactionId: 1 });
    // appleTransactionLinks._id = originalTransactionId and appleNotifications._id = notificationUUID
    // are both naturally unique; these two index the support-lookup direction ("everything Apple sent
    // about this player") and the reverse link lookup ("which subscriptions does this account own").
    await collections.appleTransactionLinks.createIndex({ accountId: 1 });
    await collections.appleNotifications.createIndex({ accountId: 1, ts: -1 });
    await collections.appleNotifications.createIndex({ originalTransactionId: 1 });
    // appleAccountTokens._id = the token; the unique index the other way round is what makes allocation
    // idempotent -- two concurrent /bootstrap calls for the same account cannot end up with two
    // tokens, which would split one player's purchases across two identities Apple reports.
    await collections.appleAccountTokens.createIndex({ accountId: 1 }, { unique: true });
    // appleConsumptionConsents._id = accountId is naturally unique; nothing scans it.
    // recharges._id = receiptId is naturally unique; wallets._id = accountId is naturally unique.
    // promoCodes._id = code is naturally unique; promoRedemptions._id = accountId:code is naturally unique.
    await collections.promoRedemptions.createIndex({ accountId: 1, ts: -1 });
    // gachaPools._id = pool id is naturally unique; index the active window for listing open limited pools.
    await collections.gachaPools.createIndex({ endAt: 1 });
  }

  return {
    client,
    db,
    collections,
    ensureIndexes,
    close: () => client.close(),
  };
}
