// Commercial database factory (S5-1, COMMERCIAL_DESIGN §3/§7). Database name notebook_wars_commercial,
// physically isolated from the meta database. Collections: wallets / ledger / orders / recharges / gachaHistory.
import { MongoClient, Db, Collection, type MongoClientOptions } from 'mongodb';
import type { Rarity } from '@nw/shared';

/** Balance (single-document atomic update + optimistic lock rev). pity embedded in the same document (design default A: coin deduction + pity counter in one atomic operation). */
export interface WalletDoc {
  _id: string; // accountId
  coins: number; // >= 0
  rev: number;
  gacha: { pity: Record<string, number> }; // poolId → cumulative draws since last legendary
  /** Timestamp of first-ever successful IAP (ms). Absent = never purchased; gates the first-purchase 2× bonus. */
  firstPurchasedAt?: number;
  updatedAt: number;
}

/** Immutable ledger entry (one record per credit/debit, for auditing/reconciliation). */
export interface LedgerDoc {
  accountId: string;
  delta: number;
  balanceAfter: number;
  reason: string; // shop | gacha | gacha_refund | recharge | ads
  orderId?: string;
  receiptId?: string;
  ts: number;
}

export interface GachaResultEntry {
  itemId: string;
  rarity: Rarity;
}

/** Purchase order (idempotency key orderId + pending delivery reconciliation saga). */
export interface OrderDoc {
  _id: string; // orderId (UUID generated by meta)
  accountId: string;
  // 'sink' = pure coin consumption (e.g. rename), no item delivery, lands in DB as status:'delivered', not picked up by reconciliation.
  // 'grant' = pure coin grant (mail attachment claim S6-3), same as sink: delivered on insert, not picked up by reconciliation.
  kind: 'shop' | 'gacha' | 'sink' | 'grant';
  cost: number;
  status: 'charged' | 'delivered';
  coinsAfter: number; // balance after coin deduction (for idempotent replay)
  result: { itemId?: string; results?: GachaResultEntry[]; poolId?: string };
  pityAfter?: Record<string, number>;
  refundCoins?: number; // duplicate refund coins computed by meta in the delivery callback (credited on delivered)
  deliveredAt?: number;
  ts: number;
}

/** Top-up receipt (idempotency key receiptId + duplicate coin prevention). */
export interface RechargeDoc {
  _id: string; // receiptId
  accountId: string;
  platform: string;
  coinsGranted: number;
  status: 'granted';
  rawReceipt: string;
  ts: number;
}

/** Gacha draw history (persisted per draw, M7). */
export interface GachaHistoryDoc {
  accountId: string;
  poolId: string;
  orderId: string;
  results: GachaResultEntry[];
  pityBefore: number;
  pityAfter: number;
  ts: number;
}

/** Daily victory coin claim counter (_id=`accountId:dayKey` → number of wins paid out so far), enforces the daily cap. */
export interface VictoryDailyDoc {
  _id: string; // `${accountId}:${dayKey}`
  accountId: string;
  dayKey: string;
  wins: number; // wins paid out today (capped at VICTORY_DAILY_WIN_CAP)
  ts: number;
}

/** Promo code definition (B-PROMO). _id = code string (normalized to uppercase). */
export interface PromoCodeDoc {
  _id: string; // code (already normalized to uppercase)
  coins: number; // coins granted on redemption
  expiresAt?: number; // expiry timestamp (ms), defaults to never
  totalLimit?: number; // global redemption cap (defaults to unlimited)
  redeemed: number; // number of times redeemed (atomic $inc)
  note?: string; // operator note
  createdBy: string; // adminId
  createdAt: number;
}

/** Promo code redemption record (B-PROMO). _id = `${accountId}:${code}` is naturally unique, preventing duplicate redemptions. */
export interface PromoRedemptionDoc {
  _id: string; // `${accountId}:${code}`
  accountId: string;
  code: string;
  coinsGranted: number;
  ts: number;
}

export interface CommercialCollections {
  wallets: Collection<WalletDoc>;
  ledger: Collection<LedgerDoc>;
  orders: Collection<OrderDoc>;
  recharges: Collection<RechargeDoc>;
  gachaHistory: Collection<GachaHistoryDoc>;
  victoryDaily: Collection<VictoryDailyDoc>;
  promoCodes: Collection<PromoCodeDoc>;
  promoRedemptions: Collection<PromoRedemptionDoc>;
}

export interface CommercialMongo {
  client: MongoClient;
  db: Db;
  collections: CommercialCollections;
  ensureIndexes(): Promise<void>;
  close(): Promise<void>;
}

export async function createCommercialMongo(
  uri: string,
  dbName: string,
  options?: MongoClientOptions,
): Promise<CommercialMongo> {
  const client = new MongoClient(uri, options);
  try {
    await client.connect();
  } catch (err) {
    // On connection failure, log a clear, redacted error message before rethrowing to avoid a silent crash during startup.
    const safeUri = uri.replace(/\/\/[^@/]*@/, '//<redacted>@');
    console.error(
      `[commercial-mongo] Failed to connect to MongoDB (uri=${safeUri}, db=${dbName}): ` +
        `${(err as Error).message}. Please ensure the database is running and the connection config (NW_COMM_MONGO_URI/NW_MONGO_URI) is correct.`,
    );
    throw err;
  }
  const db = client.db(dbName);
  const collections: CommercialCollections = {
    wallets: db.collection<WalletDoc>('wallets'),
    ledger: db.collection<LedgerDoc>('ledger'),
    orders: db.collection<OrderDoc>('orders'),
    recharges: db.collection<RechargeDoc>('recharges'),
    gachaHistory: db.collection<GachaHistoryDoc>('gachaHistory'),
    victoryDaily: db.collection<VictoryDailyDoc>('victoryDaily'),
    promoCodes: db.collection<PromoCodeDoc>('promoCodes'),
    promoRedemptions: db.collection<PromoRedemptionDoc>('promoRedemptions'),
  };

  async function ensureIndexes(): Promise<void> {
    await collections.ledger.createIndex({ accountId: 1, ts: -1 });
    await collections.orders.createIndex({ accountId: 1, status: 1 });
    // Reconciliation scan: undelivered orders (status:'charged') by time.
    await collections.orders.createIndex({ status: 1, ts: 1 });
    await collections.gachaHistory.createIndex({ accountId: 1, ts: -1 });
    // recharges._id = receiptId is naturally unique; wallets._id = accountId is naturally unique.
    // promoCodes._id = code is naturally unique; promoRedemptions._id = accountId:code is naturally unique.
    await collections.promoRedemptions.createIndex({ accountId: 1, ts: -1 });
  }

  return {
    client,
    db,
    collections,
    ensureIndexes,
    close: () => client.close(),
  };
}
