/**
 * cityAtlasLoader.ts — SLG city (main base) sprite atlas loader.
 *
 * Hand-drawn city images at 256 px each, one dedicated frame per level (`city_l1..city_l10`).
 * Source atlas regenerated by art/ui/slg-building/pack_city_atlas.js into
 * `assets/slg/city_atlas.{png,json}`, then folded into the shared `assets/slg/world_atlas.{png,json}`
 * (see worldAtlas.ts). Until 2026-08-14 levels 1/3/6/9 had no dedicated art and fell back to 4
 * pre-redesign "tier" frames (`city_lv1..lv4`); once the last of those was redrawn, all 10 levels
 * were unified onto the flat `city_l{level}` naming and the tier fallback was dropped (see
 * design/product/city-image-prompts.md).
 *
 * Used by WorldMapScene to render each base tile as a 3×3-tile sprite that
 * overrides the programmatic city icon once the atlas is decoded.
 */
import type * as PIXI from 'pixi.js-legacy';
import { worldAtlas as atlas } from './worldAtlas';
import atlasData from '../../assets/slg/world_atlas.json';

/** True once the atlas PNG has decoded and frames are parsed. */
export const isCityAtlasReady = atlas.isReady;

/** Texture for a specific city LEVEL (1–10): the dedicated frame `city_l{level}`. */
export function getCityTextureForLevel(level: number): PIXI.Texture | null {
  if (!atlas.isReady()) return null;
  const lv = Math.max(1, Math.min(10, Math.round(level)));
  return atlas.getTexture(`city_l${lv}`);
}

/**
 * Fraction (0-1) of the packed 256px cell that's transparent padding above the bottom-aligned
 * building art, for the same frame getCityTextureForLevel(level) would resolve — see the
 * `contentTop` field pack_city_atlas.js bakes into city_atlas.json. Every level fills a different
 * amount of the fixed cell (a lv1 camp barely reaches halfway; a lv10 citadel nearly fills it), so
 * anything positioning itself off the sprite's full height (e.g. the city-layer HP bar in
 * WorldMapRenderer/city.ts) needs this to land just above the ACTUAL art instead of floating above
 * mostly-empty padding. Falls back to 0 (assume the art fills the cell) if the atlas predates this
 * field. Unlike getCityTextureForLevel, this doesn't need the PNG decoded (no `sheet` gate) — the
 * value comes straight off the bundled JSON, available as soon as the module loads.
 */
export function getCityContentTopFracForLevel(level: number): number {
  const lv = Math.max(1, Math.min(10, Math.round(level)));
  const frames = (atlasData as { frames: Record<string, { contentTop?: number }> }).frames;
  return frames[`city_l${lv}`]?.contentTop ?? 0;
}

/**
 * Decode + parse the shared world atlas. Idempotent; concurrent calls share one
 * in-flight promise. Failure is non-fatal — tiles fall back to the
 * programmatic city icon.
 */
export const loadCityAtlas = atlas.load;
