/**
 * playerBaseAtlasLoader.ts — player's own base sprite atlas loader.
 *
 * Hand-drawn "stationery fortress" images, one per desk level (1-10). Source atlas
 * regenerated by art/ui/slg-playerbase/pack_playerbase_atlas.js into
 * `assets/slg/playerbase_atlas.{png,json}`, then folded into the shared
 * `assets/slg/world_atlas.{png,json}` by art/scripts/mergeAssetAtlases.js (see
 * worldAtlas.ts). Deliberately a separate atlas + theme from cityAtlasLoader's castle/fort art: this one renders
 * only the requester's own base tile (tile.mine), driven by desk building level rather than the
 * tile's terrain-generated `level`. Other bases and NPC map cities keep using cityAtlasLoader.
 */
import type * as PIXI from 'pixi.js-legacy';
import { worldAtlas as atlas } from './worldAtlas';
import atlasData from '../../assets/slg/world_atlas.json';

/** True once the atlas PNG has decoded and frames are parsed. */
export const isPlayerBaseAtlasReady = atlas.isReady;

/** Texture for the player's own base at a given desk level (1-10). No tier fallback — every level has its own frame. */
export function getPlayerBaseTextureForLevel(level: number): PIXI.Texture | null {
  const lv = Math.max(1, Math.min(10, Math.round(level)));
  return atlas.getTexture(`playerbase_l${lv}`);
}

/**
 * Fraction (0-1) of the packed 256px cell that's transparent padding above the bottom-aligned
 * building art — see cityAtlasLoader.getCityContentTopFracForLevel for why this matters (the
 * city-layer HP bar in WorldMapRenderer/city.ts needs it to avoid floating above short buildings).
 * Falls back to 0 if the atlas predates the `contentTop` field. Unlike getPlayerBaseTextureForLevel,
 * this doesn't need the PNG decoded (no `sheet` gate) — the value comes straight off the bundled
 * JSON, available as soon as the module loads.
 */
export function getPlayerBaseContentTopFracForLevel(level: number): number {
  const lv = Math.max(1, Math.min(10, Math.round(level)));
  const frames = (atlasData as { frames: Record<string, { contentTop?: number }> }).frames;
  return frames[`playerbase_l${lv}`]?.contentTop ?? 0;
}

/**
 * Fraction (0-1] of the packed 256px cell's WIDTH actually filled by content — mirrors
 * {@link getPlayerBaseContentTopFracForLevel} but for the horizontal axis (2026-08-08, see
 * pack_playerbase_atlas.js's `contentWidthFrac`). Not currently consumed by the renderer (the sprite
 * is always scaled to the full `BASE_SPRITE_TILES`-wide square regardless), but exposed so
 * cityAtlasContentTop.ui.ts can assert against the real baked value that the plot's own width is
 * actually reached — the bug this field was added to catch (`CONTENT_W_FRAC` quietly drifting back to
 * a too-small comfort margin) has no other symptom a test could see, since it doesn't change
 * `contentTop`. Falls back to 1 (assume full width) if the atlas predates this field.
 */
export function getPlayerBaseContentWidthFracForLevel(level: number): number {
  const lv = Math.max(1, Math.min(10, Math.round(level)));
  const frames = (atlasData as { frames: Record<string, { contentWidthFrac?: number }> }).frames;
  return frames[`playerbase_l${lv}`]?.contentWidthFrac ?? 1;
}

/**
 * Decode + parse the shared world atlas. Idempotent; concurrent calls share one
 * in-flight promise. Failure is non-fatal — the base falls back to the shared
 * city atlas (see WorldMapRenderer/city.ts).
 */
export const loadPlayerBaseAtlas = atlas.load;
