#!/usr/bin/env node
// Provision one least-privilege Mongo user per service (see scripts/mongoDbMap.mjs for the why and the map).
//
// Each user is created IN the database it owns, with exactly `readWrite` on that database. Authenticating
// as `nw_world` and then opening `notebook_wars_commercial` fails with an authorization error — which is
// the whole point: COMMERCIAL_DESIGN's "commercial is the only writer of coin data" stops depending on
// everyone remembering it.
//
// Usage
//   node scripts/provisionMongoUsers.mjs --uri="mongodb://root:pw@host:27017/?replicaSet=rs0"
//       Connects as an admin user and creates/updates every service user, generating a fresh random
//       password for each. Prints the resulting NW_*_MONGO_URI lines — the passwords are shown ONCE.
//
//   node scripts/provisionMongoUsers.mjs --uri=... --keep-passwords
//       Same, but leaves existing users' passwords alone (only re-applies roles). Use when rotating roles
//       without redeploying every service.
//
//   node scripts/provisionMongoUsers.mjs --emit-mongosh --local
//       Prints a mongosh program instead of connecting, using the fixed local-stack passwords. The local
//       Mongo is cluster-internal (not published to the host), so docker/local-up.ps1 pipes this into
//       `docker compose exec -T mongo mongosh`.
//
//   node scripts/provisionMongoUsers.mjs --atlas
//       Prints the `atlas` CLI commands to run instead. Atlas manages database users itself: `createUser`
//       through the driver is refused there ("not authorized on admin"), so a script that "just works"
//       against Atlas does not exist — this prints exactly what to run, with the same roles.
//
// Options
//   --uri=<admin connection string>   or env NW_MONGO_ADMIN_URI
//   --db-suffix=<s>   appends to every database name (staging clusters sharing one deployment)
//   --print-env-only  skips provisioning, prints the env lines for passwords given via NW_MONGO_PW_<USER>
import { randomBytes } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { MONGO_SERVICES, localPassword } from './mongoDbMap.mjs';

const argv = process.argv.slice(2);
const flag = (name) => argv.includes(`--${name}`);
const opt = (name) => {
  const hit = argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : undefined;
};

const LOCAL = flag('local');
const EMIT_MONGOSH = flag('emit-mongosh');
const ATLAS = flag('atlas');
const KEEP_PASSWORDS = flag('keep-passwords');
const PRINT_ENV_ONLY = flag('print-env-only');
const DB_SUFFIX = opt('db-suffix') ?? '';

/** Rows with the suffix applied, so a staging cluster can host `notebook_wars_commercial_staging` etc. */
const rows = MONGO_SERVICES.map((r) => ({ ...r, db: r.db + DB_SUFFIX }));

/**
 * The password for one service: an explicit NW_MONGO_PW_<USER> wins (re-running with known passwords is
 * how you re-apply roles without redeploying), then the fixed local one, then a fresh random secret.
 */
function passwordFor(row) {
  const fromEnv = process.env[`NW_MONGO_PW_${row.user.toUpperCase()}`];
  if (fromEnv) return { pwd: fromEnv, generated: false };
  if (LOCAL) return { pwd: localPassword(row.user), generated: false };
  return { pwd: randomBytes(24).toString('base64url'), generated: true };
}

/**
 * Rewrite an admin connection string into a per-service one: swap the credentials, force `authSource` to
 * the service's own database (that is where its user lives), and keep every other option the operator set
 * — `replicaSet`, and on Atlas the `maxPoolSize=10` that keeps 7 processes under the M0 connection cap.
 */
export function buildServiceUri(adminUri, user, pwd, authDb) {
  const m = /^(mongodb(?:\+srv)?:\/\/)(?:[^@/]*@)?([^/?]+)(\/[^?]*)?(\?.*)?$/.exec(adminUri.trim());
  if (!m) throw new Error(`unrecognised Mongo URI: ${adminUri}`);
  const [, scheme, hosts, , query] = m;
  const params = new URLSearchParams(query ? query.slice(1) : '');
  params.set('authSource', authDb);
  const cred = `${encodeURIComponent(user)}:${encodeURIComponent(pwd)}@`;
  return `${scheme}${cred}${hosts}/?${params.toString()}`;
}

/** The mongosh program: idempotent, and safe to re-run — an existing user has its roles re-applied. */
function mongoshProgram(creds) {
  const lines = [
    '// Generated by server/scripts/provisionMongoUsers.mjs — do not edit by hand.',
    'let created = 0, updated = 0;',
  ];
  for (const { row, pwd } of creds) {
    const args = JSON.stringify({ user: row.user, pwd, db: row.db, keep: KEEP_PASSWORDS });
    lines.push(
      `(() => { const a = ${args}; const d = db.getSiblingDB(a.db);`,
      '  const exists = d.getUser(a.user) !== null;',
      '  if (!exists) { d.createUser({ user: a.user, pwd: a.pwd, roles: [{ role: "readWrite", db: a.db }] }); created++; }',
      // updateUser without `pwd` re-applies roles only — that is what --keep-passwords buys.
      '  else if (a.keep) { d.updateUser(a.user, { roles: [{ role: "readWrite", db: a.db }] }); updated++; }',
      '  else { d.updateUser(a.user, { pwd: a.pwd, roles: [{ role: "readWrite", db: a.db }] }); updated++; }',
      '})();',
    );
  }
  lines.push('print(`mongo users: ${created} created, ${updated} updated`);');
  return lines.join('\n');
}

/** Create/update the users over the driver. Works against a self-hosted cluster (prod compose, local). */
async function provisionDirect(adminUri, creds) {
  const { MongoClient } = await import('mongodb');
  const client = new MongoClient(adminUri);
  await client.connect();
  try {
    for (const { row, pwd } of creds) {
      const db = client.db(row.db);
      const roles = [{ role: 'readWrite', db: row.db }];
      const existing = await db.command({ usersInfo: row.user }).catch(() => ({ users: [] }));
      if (existing.users?.length) {
        await db.command(KEEP_PASSWORDS ? { updateUser: row.user, roles } : { updateUser: row.user, pwd, roles });
        process.stderr.write(`updated ${row.user} → readWrite@${row.db}\n`);
      } else {
        await db.command({ createUser: row.user, pwd, roles });
        process.stderr.write(`created ${row.user} → readWrite@${row.db}\n`);
      }
    }
  } finally {
    await client.close();
  }
}

function printAtlasCommands(creds) {
  process.stdout.write(
    '# Atlas manages database users itself — `createUser` over the driver is refused there.\n' +
      '# Run these (atlas CLI, logged in and pointed at the right project/cluster), then paste the env\n' +
      '# lines below into server/.env and redeploy:\n\n',
  );
  for (const { row, pwd } of creds) {
    process.stdout.write(
      `atlas dbusers create --username ${row.user} --password '${pwd}' \\\n` +
        `  --role readWrite@${row.db} --projectId "$ATLAS_PROJECT_ID"\n`,
    );
  }
  process.stdout.write('\n');
}

function printEnvLines(adminUri, creds) {
  process.stdout.write('# ---- per-service Mongo credentials (passwords are shown once) ----\n');
  for (const { row, pwd } of creds) {
    process.stdout.write(`${row.uriEnv}=${buildServiceUri(adminUri, row.user, pwd, row.db)}\n`);
  }
  process.stdout.write(
    '# NW_MONGO_URI above is metaserver\'s own login. Keep the cluster admin string OUT of server/.env:\n' +
      '# no service needs it, and a compose block that carries it is exactly what this change removes.\n',
  );
}

async function main() {
  const adminUri = opt('uri') ?? process.env.NW_MONGO_ADMIN_URI ?? '';
  const creds = rows.map((row) => ({ row, ...passwordFor(row) }));

  if (EMIT_MONGOSH) {
    process.stdout.write(mongoshProgram(creds));
    return;
  }
  if (ATLAS) {
    printAtlasCommands(creds);
    if (adminUri) printEnvLines(adminUri, creds);
    else process.stdout.write('# pass --uri=<cluster string> to also print the NW_*_MONGO_URI lines\n');
    return;
  }
  if (!adminUri) {
    process.stderr.write('missing --uri=<admin connection string> (or NW_MONGO_ADMIN_URI)\n');
    process.exit(2);
  }
  if (!PRINT_ENV_ONLY) await provisionDirect(adminUri, creds);
  printEnvLines(adminUri, creds);
}

// Importable for tests (buildServiceUri); only runs when invoked as a script.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
