// SaveData — single authoritative root of the meta system (META_DESIGN.md §3.1). Pure data, no PIXI / no platform dependencies.
// This file is the client-side mirror; the server-authoritative copy lives in server/shared/src/types.ts. The SaveData
// schema in openapi.yml is derived from both. Changing a field requires syncing all three places + adding a migration (migrate.ts), or old saves break.

export type Rarity = 'common' | 'rare' | 'epic' | 'legendary';

export interface LevelRecord {
  timeMs?: number;
  leaked?: number;
  [k: string]: unknown;
}

// ── Equipment instance (EQUIPMENT_DESIGN §3.1). Client mirror, derived from server/shared/src/types.ts ──
export type EquipSlot = 'weapon' | 'armor' | 'trinket';
export type EquipRarity = 'common' | 'fine' | 'rare' | 'epic';

/** Affix (unified shape for primary / secondary / skill affixes). */
export interface Affix {
  id: string;
  value: number;
}

/** Equipment instance (server-authoritative, client read-only). */
export interface EquipmentInstance {
  id: string;
  defId: string;
  rarity: EquipRarity;
  level: number; // 0..9
  affixes: Affix[];
  locked?: boolean;
  /** Provenance tag ('craft'/'gacha:<orderId>'/'checkin:<monthKey>'/'pve_drop:<levelId>'). Optional —
   *  absent on pre-2026-08-04 instances; no consumer reads this yet (design/game/ITEM_IDENTITY_DESIGN.md). */
  sourceType?: string;
  /** Epoch ms when this instance was created. Optional, same caveat as sourceType. */
  obtainedAt?: number;
}

/** Slot → instance id mapping for one card's loadout. */
export type GearSlotMap = Partial<Record<EquipSlot, string /* instanceId */>>;

/**
 * Character card instance in the Hero Roster (CHARACTER_CARDS_DESIGN §2.2).
 * SLG runtime fields (currentTroops, injuredUntil) live in worldsvc PlayerWorldDoc.cardState (§6.1) — NOT here.
 */
export interface CardInstance {
  /** Unique instance id generated by the server (e.g. 'card_a1b2c3'). */
  id: string;
  /** Card definition id — references CARD_DEFS[defId] (e.g. 'lichuang', 'max'). */
  defId: string;
  /** Card level 1–9. Increases via fusion (CHARACTER_CARDS_DESIGN §3): 5 same-level same-faction materials → +1 level. */
  level: number;
  /** Per-slot equipped item instance ids (weapon/armor/trinket → equipmentInstanceId). */
  gear: GearSlotMap;
  /** Locked cards cannot be used as feed material (CC4). */
  locked: boolean;
  /** Provenance tag ('starter'/'checkin'/'pve_anchor:<levelId>'/'pve_drop:<levelId>'/'gacha:<orderId>'). Optional —
   *  absent on pre-2026-08-04 instances; no consumer reads this yet (design/game/ITEM_IDENTITY_DESIGN.md). */
  sourceType?: string;
  /** Epoch ms when this instance was created. Optional, same caveat as sourceType. */
  obtainedAt?: number;
}

export interface SaveData {
  version: number; // schema version, used for migrations
  accountId: string; // cloud-save identity (empty string = not yet obtained / local-only)
  rev: number; // monotonically increasing revision number, used for optimistic locking / conflict resolution
  updatedAt: number; // server timestamp (display only, not trusted on the client)

  // —— Server-authoritative section (client read-only, §2) ——
  // wallet/gacha are read-only mirrors of the commercial service authority since S5 (meta fills them after economic operation receipts; client never writes them).
  wallet: { coins: number };
  // Skin instance counts (ITEM_IDENTITY_DESIGN.md task1, 2026-08-08): skinId → total owned instance
  // count. `inventory.skins` below is unaffected and stays the plain owned/not-owned view every
  // pre-existing consumer reads (equip picker, etc.) — this only adds "how many" on top, e.g. so the
  // auction picker can offer a surplus duplicate for listing/selling even when one copy is equipped.
  // Additive-only field, backfilled to {} by migrate.ts's fillDefaults for any older local save — no
  // SAVE_VERSION bump needed (same convention as cardInv/equipmentInv when those were introduced).
  skinCounts: Record<string, number>;
  inventory: {
    skins: string[];
    items: Record<string, number>;
  };
  gacha: { pity: Record<string, number> };
  // Monetization mirror (GACHA_DESIGN §5–§7): read-only mirror of commercial authority. Absent in legacy saves.
  monetization?: {
    fatePoints: number; // Fate Points balance (§7)
    subscriptionExpiry: number; // monthly card end timestamp (ms); 0 = none (§5)
    subscriptionLastClaimDay?: string; // UTC day (YYYY-MM-DD) of last daily-coin claim; absent = never claimed (§5)
    starterUsed: string[]; // one-off product ids already purchased (§6)
    starterGrowthEligible?: boolean; // still inside the growth pack's first-N-days account-age window; absent = eligible (§6)
    firstPurchaseUsed?: boolean; // true once the first-purchase 2× bonus has been claimed; absent = not yet used (legacy saves)
    totalRechargeCents?: number; // lifetime cumulative real-money spend (usdCents), GACHA_DESIGN §13; absent = 0
  };
  // Delivered purchase orders (commercial orderId); server-authoritative, client read-only (S5-5).
  deliveredOrders: string[];
  pvp: {
    elo: number;
    rank: string;
    wins: number;
    losses: number;
    streak: number;
    // —— S11 season fields (may be absent in legacy saves) ——
    seasonNo?: number;
    seasonPeakElo?: number;
    seasonPeakRank?: string;
    reachedRanks?: string[];
  };
  // —— S11 battle pass (lazy-created; appears after the first ranked game or purchase this season) ——
  battlePass?: {
    seasonNo: number;
    xp: number;
    level: number;
    hasPass: boolean;
    claimedFree: number[];
    claimedPaid: number[];
  };

  // —— Cumulative recharge milestone claims (GACHA_DESIGN §13, ADR-045). Lazily created; absent = no tier ever claimed. ——
  rechargeMilestone?: {
    claimed: number[];
  };

  // —— Retention (B5, RETENTION_DESIGN). Server-authoritative; not sent up on PUT /save (client read-only). ——
  retention?: {
    checkin?: { monthKey: string; claimedDays: number[]; lastClaimedDayKey?: string };
    daily?: { dayKey: string; completedTasks: Record<string, number>; taskPoints: number; rewardClaimed: boolean };
    /** Weekly active chest progress (§12.3, ISO week key). */
    weekly?: { weekKey: string; points: number; claimedTiers: number[] };
  };

  // —— Stamina (A4, server-authoritative, not sent up on PUT /save). Regenerates 1 point every 6 min, cap 120. Absent defaults to full.
  stamina?: { current: number; regenAt: number };

  // —— Titles (S10, TITLE_DESIGN §2). Server-authoritative, not sent up on PUT /save (client read-only).
  // The equipped slot is at equipped['title'] (sync section, client-writable); servers broadcast the opponent's title from it.
  titles?: string[];
  // —— Title grant timestamps (ITEM_IDENTITY_DESIGN.md task3, 2026-08-10). Mirrors server SaveData.titleGrants,
  // read-only display use (e.g. "obtained on <date>"); GET /titles also returns per-title obtainedAt directly
  // (see net/openapi.ts), so this whole-save mirror is a secondary source, not required by any current UI.
  titleGrants?: Record<string, number>;

  // —— Lifetime-owned ledger (avatar unlock across hero/equipment/material/skin). Server-authoritative,
  // not sent up on PUT /save (client read-only). Additive-only: survives the item later being
  // salvaged/consumed/sold, unlike cardInv/equipmentInv/materials/inventory.skins themselves.
  everOwned?: {
    hero?: string[];
    equipment?: string[];
    material?: string[];
    skin?: string[];
  };

  // —— Client sync section (light validation, §2) ——
  progress: {
    cleared: string[];
    stars: Record<string, 1 | 2 | 3>;
    best: Record<string, LevelRecord>;
  };
  materials: Record<string, number>;
  /**
   * @deprecated S3-2 per-stat material upgrades. Kept for old-save compatibility; not used since the Hero Roster rework (CC-1).
   */
  pveUpgrades: Record<string, number>;
  /**
   * Cosmetic equipment (slot→skinId). Server-authoritative, client read-only outside the dedicated
   * mutation endpoints (SaveManager.equipTitle/equipAvatar/equipSkin — each with its own ownership
   * validation server-side). Two kinds of keys share this map: `title` (equipped title, TITLE_DESIGN §2)
   * and `skin:<UnitType>` (equipped skin per character, one slot per character since a skin never
   * targets more than one UnitType — see game/meta/skinDefs.ts, LOBBY_IA_REDESIGN §15).
   */
  equipped: Record<string, string>;
  /** Server-authoritative, client read-only outside SaveManager.setFlag (PUT /flags) — no per-key ownership semantics, just onboarding/consent/tutorial-seen style booleans. */
  flags: Record<string, boolean>;
  /** PvP deck builder selection (P3, PVP_LOADOUT §8). Local-only, never synced to the server at all. */
  pvpDeck?: string[];

  // —— Hero Roster (CHARACTER_CARDS_DESIGN §2.3, SAVE_VERSION 4). Server-authoritative, client read-only. ——
  // cardInv replaces unitLevels + cardInventory + gear (all removed in v4). Capacity: 150 instances.
  // Each CardInstance carries its own gear loadout (CardInstance.gear), replacing the global GearLoadout.
  cardInv: Record<string, CardInstance>;

  // —— Equipment system (server-authoritative, client read-only, EQUIPMENT_DESIGN §3.1) ——
  // Equipment instances are still tracked in equipmentInv; the loadout relationship moved into CardInstance.gear (v4).
  equipmentInv: Record<string, EquipmentInstance>;

  // —— Achievement system (server-authoritative, ACHIEVEMENT_DESIGN §3). Lazy-created: absent defaults to all-zero / empty;
  //    legacy saves are not migrated; client read-only. antiCheat is not pushed down, so the mirror excludes it. ——
  stats?: Record<string, number>; // lifetime cumulative statistics (StatKey→value), monotonically increasing
  achievements?: Record<string, { claimedTiers: number[] }>; // achId→subset of claimed tier indices
}

/**
 * Wire shape returned by the /equipment/* mutation endpoints (craft/enhance/salvage/reforge/equip)
 * (EQUIPMENT_DESIGN §3.3 phase 2, 2026-07-26) and by /gacha/draw (2026-07-28, same treatment — the
 * highest-frequency card/equipment-granting endpoint, nothing stops a player mashing "draw" back to
 * back). Unlike every other `save: SaveData` response (GET /save, pveClear, ...), these deliberately
 * send `equipmentInv`/`cardInv` as `null` — the caller already has what changed via the response's own
 * `instance`/`cardGrants`/`equipmentGrants` field, or the `instanceIds`/`materialId` it sent as request
 * params, so the server skips reassembling the full map. Kept distinct from `SaveData` (whose
 * `equipmentInv`/`cardInv` are always real maps once held in memory) so the compiler catches any
 * code that tries to read `.equipmentInv`/`.cardInv` off a lean response directly instead of going
 * through `SaveManager.adoptServerPartial`.
 */
export type LeanSaveResponse = Omit<SaveData, 'equipmentInv' | 'cardInv'> & {
  equipmentInv?: Record<string, EquipmentInstance> | null;
  cardInv?: Record<string, CardInstance> | null;
};

// v2 (2026-06-21): Added equipmentInv + gear (equipment system E0). See migrate.ts for v1→v2 migration.
// v3 (2026-06-21): Unit progression rework (S12) — added unitLevels + cardInventory, pveUpgrades marked deprecated.
// v4 (2026-07-01): Hero Roster (CC-1) — removed unitLevels + cardInventory + gear; added cardInv (CHARACTER_CARDS_DESIGN §2.3).
// v5 (2026-07-13): CollectionScene retirement (LOBBY_IA_REDESIGN §15) — skin equip moves from the single
// global `equipped['unit']` slot to one slot per character (`equipped['skin:<UnitType>']`, skinDefs.ts).
export const SAVE_VERSION = 5;

/** Primary storage key for local saves (IPlatform.storage). */
export const SAVE_STORAGE_KEY = 'nw_save_v1';

/**
 * Default save for a new account. All authoritative sections start from zero (consistent with server-side makeNewSave).
 * `titles` is server-authoritative (client read-only): the server seeds the `event.newbie` starter title at account
 * creation and syncs it down via GET /save, so it is intentionally omitted from this client-local default.
 */
export function makeNewSave(accountId = '', now = 0): SaveData {
  return {
    version: SAVE_VERSION,
    accountId,
    rev: 0,
    updatedAt: now,
    wallet: { coins: 0 },
    skinCounts: {},
    inventory: { skins: [], items: {} },
    gacha: { pity: {} },
    deliveredOrders: [],
    pvp: { elo: 1000, rank: 'unranked', wins: 0, losses: 0, streak: 0 },
    progress: { cleared: [], stars: {}, best: {} },
    materials: {},
    pveUpgrades: {},
    equipped: {},
    flags: {},
    cardInv: {},
    equipmentInv: {},
  };
}

